### ISSUE TITLE
haven::read_por

### ISSUE THREAD

**Issue by hadley** [leeper/rio#100]
I've dropped `read_por()` from haven, because it never actually worked, but that causes `R CMD check` to fail for rio. Do you think you'd be able to also drop `.por` support from rio and update to CRAN within the next two weeks?

(If you can't, I'll add `read_por()` back it, but all it will do is throw an error)

**Comment by leeper** [comment]
No problem. I was suspicious if that, actually.

**Comment by leeper** [comment]
@hadley This fix is on CRAN now.

**Comment by hadley** [comment]
Thanks! haven release will probably be a little later than expected - want to synchronise with readstat 1.0 release that's happening later this month.
