### ISSUE TITLE
feather requires R >=3.3.0

### ISSUE THREAD

**Issue by leeper** [leeper/rio#104]
feather uses the new compiler chain, so this has an implicit dependency on R 3.3.0 for at least Windows and maybe elsewhere. Do we need to bump `Depends` in DESCRIPTION?

h/t Kevin Wright

**Comment by leeper** [comment]
The solution to this may be a conditional NAMESPACE import. I've used this elsewhere, like:

```
if (.Platform$OS.type=="windows") {
    importFrom(grDevices, "bringToTop")
}
```

I imagine we could do the same thing with an OS type and R version logical statement. But I'm not sure how NAMESPACE and DESCRIPTION will play with one another if we do this.

**Comment by jsonbecker** [comment]
@pierrelafortune brought this up in #102 so I wanted to mention him here.

@leeper I think we'd have to change away from Depends down to Suggest and do a check for Windows and requireNameSpace stuff.

I didn't make this PR thinking about supporting users on older versions of R, which is my bad. I would be willing to make the changes myself, but I don't have ready access to a Windows machine for testing.
