### ISSUE TITLE
clipr and rio

### ISSUE THREAD

**Issue by mdlincoln** [leeper/rio#105]
So you raised and closed #47 about using [clipr](https://github.com/mdlincoln/clipr) _months_ ago and I was not paying one bit of attention - apologies!

Rest assured, no command-line dependencies will be added (other than those already there for xclip/xsel, allowing users of any X11-based machines like Linux or Solaris to use clipr).

**Comment by jsonbecker** [comment]
[datapasta](https://mran.microsoft.com/package/datapasta/) seems relevant to this feature.
