### ISSUE TITLE
Use rio with Shiny fileInput?

### ISSUE THREAD

**Issue by iainmwallace** [leeper/rio#108]
Hi

Is it possible to use rio to read files that are uploaded with the Shiny fileInput? 
http://shiny.rstudio.com/gallery/upload-file.html

When the file gets uploaded a temporary file name gets created with no extension which results in an error using rio, but I was wondering if anybody has found a clever workaround? 

thanks

Iain

**Comment by iainmwallace** [comment]
From the rioweb I found this approach (https://github.com/lbraglia/rioweb)

input_file_format <- tools::file_ext(inFile$name)
data_file<-import(file=inFile$datapath,format = input_file_format)

but when I try to upload .xlsx or .xls file in my app, I get an "Error: Unknown format ."

**Comment by leeper** [comment]
Are you running the most recent version of rio?

**Comment by iainmwallace** [comment]
Yeah, and I tried the latest development version. 
I am able to import the excel file directly using the import command without specifying format (within Rstudio on my mac)

**Comment by Stan125** [comment]
I had this problem while bulding [GREA](https://github.com/Stan125/GREA). Essentially, I had two options. Either you manually rename the file via `file.rename()`, or you use `file.choose()`instead, if you only deal with local files.

**Comment by iainmwallace** [comment]
Thanks for the suggestion!

This worked for me...
input_file_format <- tools::file_ext(inFile$name)
new_file_name<-paste0(inFile$datapath,".",input_file_format)
file.rename(inFile$datapath,new_file_name)
