### ISSUE TITLE
Fallback to sas7bdat.parso when haven fails

### ISSUE THREAD

**Issue by billdenney** [leeper/rio#119]
Would it be reasonable to fall back to the read.sas7bdat.parso library when reading sas7bdat files fails with haven?  This library worked for me when other libraries (haven, sas7bdat) failed.

sas7bdat.parso is at https://github.com/BioStatMatt/sas7bdat.parso

FYI, this is related to BioStatMatt/sas7bdat#9 and hadley/haven#31, but the same file read without issue using read.sas7bdat.parso.

**Comment by leeper** [comment]
I think probably not, but I'll consider it. The reasons for my initial reaction are that it (1) creates another dependency and (2) that dependency in particular relies on rJava, which is not exactly easy to get working reliably across platforms.

I'll take a look and see if it's possible to introduce changes in haven that will resolve that issue. Do those files fail under the development version of haven?

**Comment by billdenney** [comment]
Ah!  They do work with the development version of haven.

Thanks for the pointer to look there.
