### ISSUE TITLE
Multiple tables in HTML

### ISSUE THREAD

**Issue by sjackman** [leeper/rio#126]
Can the `which` parameter of `import` be used to extract the first/second/etc table from an HTML document with multiple tables?

**Comment by leeper** [comment]
Not at present. But that should be pretty easy to implement with a change to this line: https://github.com/leeper/rio/blob/master/R/import_methods.R#L333

I'll put it on the TODO list.

**Comment by sjackman** [comment]
Thanks!

**Comment by leeper** [comment]
I'm pushing an update with this feature momentarily. It will also be shipping to CRAN today.

**Comment by sjackman** [comment]
Thanks for the quick implementation! This gives a not-to-elegant but quite workable solution for reading multiple PSV tables from a Markdown document by rendering them to HTML and reading them with rio::import.

**Comment by sjackman** [comment]
Does rio have a function to extract all tables from a given document (HTML, XLSX, et c) and return a list of data frames? It would be quite useful I think, particularly a named list when the data format has names, like sheet names.

**Comment by leeper** [comment]
I am pushing a commit with support for this via a new function, `import_list()`, that will handle both a multi-object file (HTML, xlsx) OR a vector of multiple file names.

**Comment by sjackman** [comment]
Beautiful!
