### ISSUE TITLE
Installation requires Haven >0.2.1, but latest Haven version == 0.2.1

### ISSUE THREAD

**Issue by andrewrech** [leeper/rio#127]
```r
devtools::install_github("hadley/haven")
devtools::install_github("leeper/rio")
```
`Skipping install of 'haven' from a github remote, the SHA1 (b7f00cdf) has not changed since last install.`

`Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :
  namespace ‘haven’ 0.2.1 is already loaded, but > 0.2.1 is required`

**Comment by leeper** [comment]
The current version of haven on GitHub is 1.0.0, so I'm not sure how you're getting that error, actually. Perhaps try using `ghit::install_github("hadley/haven")` instead.

Hadley is planning to release haven 1.0.0 to CRAN shortly, which will be very quickly followed by a CRAN release of rio, so this will hopefully be moot by next week.

**Comment by andrewrech** [comment]
`ghit::install_github("hadley/haven")` worked! interesting...

thanks
