### ISSUE TITLE
Update to read.ods from readODS package

### ISSUE THREAD

**Issue by dannyparsons** [leeper/rio#128]
The `readODS::read.ods` function is now depreciated and replaced by `readODS::read_ods` (https://cran.r-project.org/web/packages/readODS/readODS.pdf). One of the advantages seems to be that it always returns a data frame (not a list) without needing to specify a sheet because it has a default `sheet = 1` (unlike the older version which has no default).

Could `rio` update to use the newer version? 

The old version may still be a useful option if you want to get all the sheets in a list, but I would guess this shouldn't be the default for `rio`.

**Comment by leeper** [comment]
Yes. I'll put this on the to-do list for v0.5.

**Comment by dannyparsons** [comment]
Thanks!
