### ISSUE TITLE
Conversion function to handle multi-object files

### ISSUE THREAD

**Issue by leeper** [leeper/rio#129]
If I want to update an XLS to XLSX, I have to loop over sheets. Similarly, if I want to convert an XLSX to Stata or CSV, looping is required. Because we may not know how many sheets there are a priori, this requires a `while ()` or `repeat` loop, which is annoying. A solution would be a modified `convert()` function (or wrapper for `convert()`) that turns a multi-object file into another multi-object file or set of files. One could imagine this also working with multiple files in a directory as input or output.

**Comment by jsonbecker** [comment]
If this is mostly a matter of xlsx, we could use `openxlsx::getSheetNames` and lapply over sheets. Similarly passing a directory instead of a file could lapply over dir()
