### ISSUE TITLE
Unknown format error when reading xlsx format file without an extension

### ISSUE THREAD

**Issue by Eugllena** [leeper/rio#130]
When I used "import" to read an xlsx format file which have no extension, it gave an error message: "Unknown format". I have set format = "xlsx", but the function still couldn't recognize.

The problem is because the function readxl can't recognize a file without an extension, it has been pointed out [here](https://github.com/hadley/readxl/issues/85).

Can you modify the function so that it works even with a file which has no extension but provide the code of file format.

**Comment by leeper** [comment]
Hmm...we could set this up to copy the file to a temporary directory and add an extension so it can be imported. Would that work for you?

**Comment by Eugllena** [comment]
Yes, it works. But will it be slow when the data set is big?

**Comment by leeper** [comment]
Yes, it could be.

**Comment by jennybc** [comment]
readxl now exposes read_xlsx and read_xls for reading extensionkess files. But someone still has to determine which it is, somehow.

**Comment by leeper** [comment]
@jennybc Oh, cool. I'm pushing an update to reflect that.
