### ISSUE TITLE
Confusing behaviour for CSV

### ISSUE THREAD

**Issue by christophergandrud** [leeper/rio#133]
The documentation seems to imply that when a file has a `.csv` extension `read.csv` is used by default and that `fread` is only used if `fread = TRUE`. However, `fread = TRUE` appears to be the default behaviour. 

When `fread = FALSE` it doesn't appear that `read.csv` is actually used. Here is an example: 

![screen shot 2016-11-30 at 11 01 32](https://cloud.githubusercontent.com/assets/1285805/20749951/6824606e-b6ec-11e6-9e1d-d1284e60ef25.png)

Sorry, I'm in a hurry and haven't had time to figure out what procedure is being used here, but this is the same data with `read.csv`:

![screen shot 2016-11-30 at 11 02 49](https://cloud.githubusercontent.com/assets/1285805/20749991/90d645a4-b6ec-11e6-8e55-3f1ebc0646a7.png)

Note: I'm using version 0.4.16

**Comment by leeper** [comment]
Thanks. This should now be fixed.

**Comment by christophergandrud** [comment]
Great. Thanks!
