### ISSUE TITLE
Cannot import rio created  SAS7BDAT into WPS, SAS or Stattransfer

### ISSUE THREAD

**Issue by rogerjdeangelis** [leeper/rio#135]
Glad to see you added sas7bdat for export

I was unable to read the sas dataset created by rio outside of R.

Would you consider adding an issue to the git hub readstat project
that write_sas datasets cannot be imported into SAS. I eas unable to import into
WPS(free express edition), Stattransfer or SAS.

%utl_submit_r64('
library(rio);
library(haven);
export(mtcars,"d:/rio/mtcars.sas7bdat");
');

> library(rio);library(haven);export(mtcars,"d:/rio/mtcars.sas7bdat");
NOTE: 1 lines were written to file PRINT.
Stderr output:
Error in .export.default(file = file, x = x, ...) :
  Unrecognized file format
Calls: export -> .export -> .export.default
Execution halted

%utl_submit_r64('
library(rio);
library(haven);
write_sas(mtcars,"d:/rio/mtcars.sas7bdat");
');

proc contents data="d:/rio/mtcars.sas7bdat";
run;quit;

153   proc contents data="d:/rio/mtcars.sas7bdat";
ERROR: File d:/rio/mtcars.sas7bdat is not a SAS data set.
154   run;

**Comment by leeper** [comment]
Thanks. I'll investigate.

**Comment by rogerjdeangelis** [comment]
Thanks

If I can help in any way let me know. I have SAS, WPS and StatTransfer. All can create SAS datasets.
WPS and StatTranfser do not require SAS. I am somewhat familiar with the binary file structure of SAS datasets and SAS CPORT files. You might take a look at Carolina, which uses JDBC to create SAS datasets?

**Comment by leeper** [comment]
@rogerjdeangelis Thanks. All the SAS read/write is actually performed by [haven](https://github.com/hadley/haven), so rio is just providing a skin around that. It's possible rio is introducing problems, though, so I'll investigate that and then possibly redirect this to Hadley.

**Comment by leeper** [comment]
@rogerjdeangelis Can you try this again using the current (GitHub) version of rio?

**Comment by rogerjdeangelis** [comment]
Thanks for the inquiry

I could not install github rio using a SAS command line pipe for some
reason it failed to identify .libpath.

I did install the latest 'have' readstat package from haven github.

Using the latest github haven package (same errors)

SAS, WPS and Stattransfer could not read sas7bdats created using
haven/readstat
Does not look like there has been an update over the last three months?
I commend you and Evan efforts, because this is not an easy task.
I am familiar with SAS cport. xport and sas7bdat formats, but failed.

  1. Read ouput SAS dataset with SAS

      ERROR: File SD1.CARS.DATA is not a SAS data set.

  2. With WPS

      I/O error: file does not have the expected structure

  3. Stattransfer

     05/14/17 13:11:55: Error:       Error reading dictionary - SAS dataset
(D:/sd1/cars.sas7bdat)

*____
|  _ \
| |_) |
|  _ <
|_| \_\
;

%utl_submit_r64('
source("C:/Program Files/R/R-3.4.0/etc/Rprofile.site", echo=T);
library(haven);
write_sas(mtcars, "d:/sd1/cars.sas7bdat");
');

libname sd1 "d:/sd1";
data ecars;
  set sd1.cars;
run;quit;

68    data ecars;
69      set sd1.cars;
ERROR: File SD1.CARS.DATA is not a SAS data set.
70    run;

*_        ______  ____
\ \      / /  _ \/ ___|
 \ \ /\ / /| |_) \___ \
  \ V  V / |  __/ ___) |
   \_/\_/  |_|   |____/

;

%utl_submit_wps64('
libname sd1 "d:/sd1";
options set=R_HOME "C:/Program Files/R/R-3.4.0";
proc r;
submit;
source("C:/Program Files/R/R-3.4.0/etc/Rprofile.site", echo=T);
library(haven);
data(mtcars);
write_sas(mtcars, "d:/sd1/cars.sas7bdat");
endsubmit;
run;quit;
proc print data=sd1.mtcar(obs=10);
run;quit;
');

proc print data=sd1.cars;
run;quit;

ERROR: Error opening data set "SD1.cars" :
       I/O error: file does not have the expected structure
NOTE: Procedure PRINT was not executed because of errors detected
11        run;

*    _        _   _                        __
 ___| |_ __ _| |_| |_ _ __ __ _ _ __  ___ / _| ___ _ __
/ __| __/ _` | __| __| '__/ _` | '_ \/ __| |_ / _ \ '__|
\__ \ || (_| | |_| |_| | | (_| | | | \__ \  _|  __/ |
|___/\__\__,_|\__|\__|_|  \__,_|_| |_|___/_|  \___|_|

;

STAT Transper

05/14/17 13:11:55:
**********************************************************************************
05/14/17 13:11:55: Reading D:/sd1/cars.sas7bdat
05/14/17 13:11:55: Input format - SAS
05/14/17 13:11:55: Error:       Error reading dictionary - SAS dataset
(D:/sd1/cars.sas7bdat)
Processing sas dataset dictionary was stopped because of the error (6).

**Comment by WERNER-E** [comment]
Hi (you two) 👍 
I do experience the same (having loaded rio today).  Is there any progress ?
To Roger :  what would be the second-best but working way to transfer data comfortably from R to SAS ?
Werner

**Comment by rogerjdeangelis** [comment]
Lossless  fast methods? xport is not lossless on unix due to IBM 8 bit
exponents instead of IEE 11 bit exponents. Larger numbers are lost?

I will put together a github project, here are my thoughts

1. Install the free WPS Express, it does not limit the size of the output
SAS dataset from R.
2. For a numeric matrix of double floats output a binary file with back to
back IEE floats.
   This is extremely fast in R since no conversion is needed. Converting
floats to text is
   very expensive. SAS can quickly load the back to back binary file of
floats.
3. If I have many moderate(not big) size dataframes to output I like to
output all of them  to one MS access
   database and then import to SAS. MySQL is also possible, but you need
SAS access products.
4. Unfortunately neither R nor SAS support the latest Dbase which does
handle doubles?

**Comment by WERNER-E** [comment]
@Roger and @leeper :   Have you obtained/given any further feedback ?
a. I had thought that  haven  could do the job  and  rio  would make it easier   ...........
b. Mostly we work (educate) under  Windows 64.  Last term I used  SAS  and  SAS EMiner  in my course. No deep learning for example, but things went very swift.
Now I wanted to expand  using  SAS  |  R  and  Python. And I had the idea that the datasets from my R examples  could be brought to  SAS and Python  ;  of my  SAS examples to  R  and Python ; etc.
Either without loss  or with minimal loss :  I would say check the agreement of  proc means and summary on the first  n digits  (n=10 or so)  and declare agreement being aware of subtleties (references ....).
That's quick and dirty, but life is so short.
If possible I would want to avoid new systems as  WPS, thought packages would do the job.
As we have SAS licenses I now try to use the foreign package and run the import job in SAS.
Simply speaking (I'm old fashioned) : If  rio  does not work with SAS it should not proclaim to do so.

**Comment by leeper** [comment]
I'm going to close this issue. Given rio doesn't do the file reading itself - that's actually done by `haven::read_sas()` and `haven::read_xpt()` - these sound like problems with haven, not rio. Happy to re-open if it become clear that they are indeed a rio-level problem.
