### ISSUE TITLE
License with MIT

### ISSUE THREAD

**Issue by hadley** [leeper/rio#14]
Would there be any chance of re-licensing as MIT? (This would require checking that it's ok with all authors).

We're planning on a revamped file import interface for RStudio, and are considering using rio. A MIT license would make this decision easier as it means we could bundle with Rstudio, if needed.

**Comment by hadley** [comment]
Sorry, this was a bit pre-emptive. We need to double check exactly what we need - we'll re-open once we've verified that we'd definitely use rio.

**Comment by leeper** [comment]
@hadley Sure, just keep me posted.
