### ISSUE TITLE
Multiple Sheets in Excel

### ISSUE THREAD

**Issue by jrjohnson0821** [leeper/rio#141]
If this is obvious in the documentation, I apologize.  How would I load multiple sheets in excel?  The documentation did not seem clear to me about what argument to pass to change sheets from the first.

**Comment by leeper** [comment]
Set `which = 2`, `which = 3`, etc. Documentation could probably be better on this.

**Comment by jennybc** [comment]
Not sure what the rio interface would be, but I just encountered this example for `readxl::excel_sheets()`:

``` r
# To load all sheets in a workbook, use lapply
path <- system.file("extdata/datasets.xls", package = "readxl")
lapply(excel_sheets(path), read_excel, path = path)
```

**Comment by leeper** [comment]
Interesting. I've been thinking of adding a list import function that would return a list of data frames to use, e.g., with an Excel workbook or a vector of files. Haven't decided on the interface yet, though.

**Comment by jsonbecker** [comment]
I would be in favor of all `which > 1` returning lists of data.frames.

We could also add a `load_directory` function that used `lapply(dir(x), import)` internally.
