### ISSUE TITLE
Export Multiple Sheets to Excel

### ISSUE THREAD

**Issue by jrjohnson0821** [leeper/rio#142]
Similar to my previous issue, is there a way to write multiple data.frames to a single excel workbook?  From what I can tell in the documentation, you're using a similar function to write.xlsx, but it doesn't allow you to pass it multiple data frames in the form of a list, like below.  Is there a way to do this that I'm just missing?  

```
list_of_datasets <- list("45days" = days45, "14days" = days14, "piv14a" = piv14a, "piv14a1" = piv14a1, "piv14b" = piv14b, "piv14c" = piv14c, "piv45" = piv45)
write.xlsx(list_of_datasets, file = "IT Queries R.xlsx")

```

**Comment by leeper** [comment]
There's no simple way to do this, but it's a good idea.
