### ISSUE TITLE
Drop readxl (and lose xls import support) and just rely just on openxlsx

### ISSUE THREAD

**Issue by leeper** [leeper/rio#145]
Thoughts?

**Comment by chainsawriot** [comment]
I personally need xls import. But maybe I am a minority.

Perhaps a better solution is to let readxl write xlsx....

**Comment by leeper** [comment]
@chainsawriot Yes, that's what I've been hoping for (https://github.com/leeper/rio/issues/96). Good to know you're using xls. I'm not eager to remove it, so at this point I'm just thinking about future behavior.

**Comment by jennybc** [comment]
Writing simple data frames (not formatting) is now on the horizon for readxl https://github.com/tidyverse/readxl/issues/231 fyi.
