### ISSUE TITLE
Consider moving openxlsx to Imports

### ISSUE THREAD

**Issue by pkq** [leeper/rio#150]
Currently, `.xlsx` is the only format for which `import()` works on a fresh install of **rio** but `export()` does not. For all other formats where both functions are supported, you can either do both without running `install_formats()` (e.g., `.csv`), or neither (e.g., `.csvy`). For consistency, does it make sense to move `openxlsx` to Imports?

**Comment by leeper** [comment]
Yes, probably a good idea. No need for a PR. I'll make a decision on this before next CRAN release.

**Comment by pkq** [comment]
Sounds good, thanks. Do you have a sense yet for when that might be? Just realized that, at the moment, the directions to run `install_formats` only apply to the development version, which may be confusing. I'd be happy to help clarify, but may not be worth it if this version is going to CRAN soon.
