### ISSUE TITLE
R rio - csv.zip writing to incorrect directory 

### ISSUE THREAD

**Issue by gbisschoff** [leeper/rio#154]
When zipping a file to a directory other than the working directory, the file is zipped to the working directory. E.g. 
I have the following folder structure.
-- workDir
     -- in
     -- out
 Running `export(foo,file.path(data.out,"foo.csv.zip"))`
creates foo.csv in the out folder, then during the zip is zipped to the working directory. After which foo.csv is deleted and the zip stays in the working directory.

 It will be a quick fix pointing the zip arguments to the new directory.

PS I really love this package.

**Comment by leeper** [comment]
Thanks for reporting. Will get this fixed.

**Comment by leeper** [comment]
@gbisschoff  I have just looked into this and I cannot reproduce it. Does it occur in the development version of rio from GitHub? If so, can you provide `sessionInfo()`.

**Comment by gbisschoff** [comment]
Hi @leeper,  I was using Rio version 0.5.0, but after upgrading to 0.5.5 it worked correctly.
This can be closed.

Thanks so much.

Just as a quick side note, are you planning to incorporate Apache Spark/Hadoop in the future? Or support for parquet files? I think it would be very useful.

**Comment by leeper** [comment]
Okay, great.

On Spark/Hadoop/Parquet, I've tossed this idea around a bit but haven't yet implemented it. Any kind of database-type file requires more dependencies so I've been a bit averse to it but if demand is there it's definitely worth implementing.
