### ISSUE TITLE
Support for .DAT files?

### ISSUE THREAD

**Issue by dannyparsons** [leeper/rio#155]
Could `rio` add support to import text based .DAT files? `data.table::fread` imports such files e.g.

```
filename <- "http://www.nilu.no/projects/ccc/onlinedata/ozone/CZ03_2009.dat"
data.table::fread(filename)
```
but it's not currently a supported file type of `rio`
```
rio::import(filename, format = ".dat")
# Unrecognized file format. Try specifying with the format argument.
# Unrecognized file format. Try specifying with the format argument.
# Error in .import.default(file = file, ...) : Format not supported
```

Would be a useful addition I think as text data often comes in this format.

**Comment by leeper** [comment]
What format is that actually? The .dat extension seems to be a generic extension applied to many different kinds of file formats and it's hard to justify assuming one of those anytime it occurs.

**Comment by dannyparsons** [comment]
That's right, in general it can be any file format. However, it seems to be fairly common to store ASCII data files with a .dat extension. There's even an example of it in the `data.table::fread` help https://rdrr.io/cran/data.table/man/fread.html (line 102)

I was thinking the only sensible things to do with a .dat file is to pass it to `data.table::fread` regardless of the actual file format. If it turns out it's not a format `fread` can read as a data frame then it would probably throw an appropriate error.

**Comment by leeper** [comment]
I'll think about how to implement that.

Note: this has come up before and we deferred. https://github.com/leeper/rio/issues/98

**Comment by dannyparsons** [comment]
Great thanks.
