### ISSUE TITLE
Bug in export to xlsx when `overwrite = TRUE` and specified sheet

### ISSUE THREAD

**Issue by leeper** [leeper/rio#156]
Behavior here is not well-defined. If I specify a sheet and `overwrite = TRUE`, should this overwrite the entire file? That's [current behavior](https://github.com/leeper/rio/blob/master/R/export_methods.R#L190) but seems wrong. Seems like it should overwrite the *sheet*, not the entire file.

Alternatively, perhaps the default should be `overwrite = FALSE`.

**Comment by pkq** [comment]
FWIW, I was surprised by this behavior today, as I assumed that the `overwrite` option applied only to the specified sheet. The behavior as of 0.5.6 seems like an improvement (i.e., that when you specify an existing sheet name, only that sheet is updated, regardless of what `overwrite` is set to. Given that change, I wonder if the option would be better named `replace_file`, with a default of `FALSE`?

**Comment by leeper** [comment]
Yea, perhaps it should be `overwrite = FALSE` as the default, but allow character arguments `overwrite = "sheet"` to allow overwrite of sheet within existing file, and `overwrite = "file"` to overwrite the file entirely.

**Comment by pkq** [comment]
This seems like a more straightforward (and less destructive) approach. What would happen when the user specifies an existing sheet name in `which`, but doesn't set `overwrite`? An error message?

**Comment by leeper** [comment]
It's a bit confusing really because if you try to overwrite a file in R, it will just happen silently (thus the original default of `overwrite = TRUE`), presumably a consistent API would have the same apply to the `which` argument. The confusing case is overwriting one sheet within an existing file versus overwriting the file with a single named sheet. The case you mention @pkq should presumably be an error but diverges from the normal behavior of other R export function (including `export()`).

**Comment by pkq** [comment]
In that case, is `overwrite` even needed? Would it work if: 
- when `which = NULL`, the entire file is overwritten,
- when `which = an_existing_sheet_name`, only that sheet is overwritten, and 
- when `which = a_nonexistent_sheet_name`, a new sheet is created? 

Are there other permutations I'm not thinking of?

**Comment by leeper** [comment]
That sounds really good.

**Comment by pkq** [comment]
Simpler and more consistent? Sounds like a win-win for sure.

**Comment by pkq** [comment]
Awesome! Thanks again for providing such a useful package!
