### ISSUE TITLE
import_list() should set file names on list elements

### ISSUE THREAD

**Issue by leeper** [leeper/rio#162]
If `rbind = FALSE`, the list should retain names corresponding to file elements here: https://github.com/leeper/rio/blob/master/R/import_list.R#L80-L89

**Comment by dannyparsons** [comment]
@leeper this is exactly what I was looking for for Excel files. But I see it only works when `which` is not provided. Is that deliberate? I'd still like to have a named list when I choose a subset of the sheets i.e. `rio::import_list("mydata.xlsx", which = 1:2)`
