### ISSUE TITLE
Add Eviews import

### ISSUE THREAD

**Issue by bdemeshev** [leeper/rio#163]
I am a big fun of R and open source :) But many of my collegues work with Eviews. To convert them into the open-source religion I would appreciate much easy import from eviews `.wf1` workfiles. 

R package hexView can do that with the old eviews format at least.

* readEViews function in [hexView](https://cran.r-project.org/web/packages/hexView/)
* [Format description](http://ricardo.ecn.wfu.edu/~cottrell/eviews_format/) by Allin Cottrell
* [demo eviews files](http://www.eviews.com/download/data/pindyck.zip) from Eviews web-site

**Comment by leeper** [comment]
Thanks. This is now supported.

**Comment by bdemeshev** [comment]
Thank you :)
