### ISSUE TITLE
Feature Request: Standardize stringsAsFactors

### ISSUE THREAD

**Issue by billdenney** [leeper/rio#166]
(This is related to #132; please incorporate it in there if you feel it is a better fit there.)

Some import methods automatically import character strings as factors; others keep them as character strings.  I like that `import` typically imports data as character rather than factors, but it would be helpful if that interface were standardized across all file types.  I specifically found that when I received a file first as `.sas7bdat` then a new version as a `.xpt` file, `.xpt` loads all character strings as factors.

My request (that I'll be happy to provide a pull request for if interested) is:

Can `stringsAsFactors` be implemented for every file type with an interface something like the following:
* If `FALSE` (the proposed new default):
    * If the loading method includes a `stringsAsFactors` argument, `FALSE` will be passed to that loading method.
    * If the loading method does not have a `stringsAsFactors` argument, the data will be loaded, and any factors in the output will be coerced to character strings.
* If `TRUE`:
    * If the loading method includes a `stringsAsFactors` argument, `TRUE` will be passed to that loading method.
    * If the loading method does not have a `stringsAsFactors` argument, the data will be loaded, and any character strings in the output will be coerced to factors.
* If `"native"` (a character string of the word native), the default for the input method will be used (no `stringsAsFactors` argument will be used in the native call to the loading function).

**Comment by leeper** [comment]
I'm pretty committed to having none of the functions return stringsAsFactors and not making this an option anywhere. If something it's returning factors, we should consider it a bug (provided the underlying import function gives us the ability to control it). XPT should return strings, for example, as import is being done by haven. Flag it as a bug if it's not working!
