### ISSUE TITLE
Feature Request: export get_ext

### ISSUE THREAD

**Issue by billdenney** [leeper/rio#169]
I find myself needing to know the extension of files that I'm loading relatively often, and I need to have different behavior based on the extension (e.g. specify `na` when reading .xlsx but don't specify it when reading .sas7bdat).

Can you please export `get_ext` so that I don't have to use the bad behavior of pulling it out with `rio:::get_ext`? :)

**Comment by leeper** [comment]
Definitely. Would you rather have it in rio or should I move that over to a standalone package?

**Comment by billdenney** [comment]
I pretty much solely use rio to load my data, so I'm happy with it in rio.

**Comment by leeper** [comment]
This is now available in the dev version here on Github.

**Comment by billdenney** [comment]
Thanks!
