### ISSUE TITLE
Can't open rio created .sav files (in read.spss() from foeign R package).

### ISSUE THREAD

**Issue by adpgithub** [leeper/rio#172]
Hi,
The 'rio' is great R package. I found one issue though. When I save my data frame to .sav file and try to open this file using read.spss()  ( from 'foreign' package) I get an error message. Kindly, let me know if there is a workaround or this issue will be fixed in coming versions.
I tried following:

    library(rio)
    library(foreign)
    export(mtcars, "D:/mtcars.sav")
    dframe <- read.spss(file="D:/mtcars.sav")

The last line above produced following error:

    Error in read.spss(file = "D:/mtcars.sav") : 
    error reading system-file header
    In addition: Warning message:
    In read.spss(file = "D:/mtcars.sav") :
    D:/mtcars.sav: Number of elements per case (0) is not between 1 and 134217727

**Comment by leeper** [comment]
This doesn't really surprise me, as the {foreign} package is basically unmaintained these days. I wouldn't use `foreign::read.spss()`.
