### ISSUE TITLE
Would an eventual patch supporting importing plaintext accounting file registers be welcome?

### ISSUE THREAD

**Issue by trevorld** [leeper/rio#173]
Hi, I currently have an alpha version of a package that can read in the registers from ``ledger``, ``hledger``, and ``beancount``[ plaintext accounting files](http://plaintextaccounting.org/) as a data frame: https://github.com/trevorld/ledgeR

When the package reaches beta would a patch contributing an ``.import_beancount``, ``.import_bean``, ``.import_ledger``, and ``.import_hledger`` to ``rio`` be welcome?  Each of them would essentially be aliases for ``ledgeR::register``.  We'd need to add ``ledgeR`` to ``rio``'s ``Suggests`` field.  Additionally in order to actually import the format the user would also need the relevant open-source program installed on their machine of either ``ledger (>= 3.1)``, ``hledger (>= 1.4)``, or ``beancount`` plus ``hledger (>= 1.4)``.

Or would it be better to add those import methods to my package and add ``rio`` to the ``Enhances`` field in my ``DESCRIPTION``?

**Comment by leeper** [comment]
Given that your package as system dependencies, I wouldn't want to include support directly here. Happy to take a PR here: https://github.com/leeper/rio/blob/master/R/extensions.R to include your package as suggested import tool for those formats, though.
