### ISSUE TITLE
Removing the labelled class from SPSS input breaks haven::as_factor()

### ISSUE THREAD

**Issue by pkq** [leeper/rio#174]
When importing an SPSS file using rio, the `standardize_attributes()` function removes the `labelled` class that haven applies. This prevents the use of `haven::as_factor()` to convert those variables to proper factors. 

The obvious work around is to call `read_sav()` directly, rather than `import()`, but one of the selling points of rio is the simplicity of being able to import a wide variety of files with one function. Is there a benefit to removing the `labelled` class that I'm missing? Would it make sense to have an optional argument to retain the class, especially considering there's already a function to restore it when exporting?

Thanks again for one of my most-used packages!

**Comment by leeper** [comment]
Have you tried `rio::factorize()` ? The reason for removing the labelled class is that it doesn't play with anything in R really. Dropping it makes those variable directly usable; `factorize()` and `characterize()` will coerce them to factor or character.

I'm open to suggestions for improved behavior.

**Comment by pkq** [comment]
I had not. In fact, I hadn't even realized `rio::factorize()` existed (despite it being referenced in the import documentation), but it does exactly what I was trying to do! It feels like there should be a way to feature the function more prominently, but I'm not sure what that is. Maybe it's just me being stuck in trying to accomplish the task using the tool I was already familiar with (i.e., `haven::as_factor()`.
