### ISSUE TITLE
Add support for SAS transport (xport) files

### ISSUE THREAD

**Issue by gwarnes-mdsol** [leeper/rio#175]
The SAS transport format (.xport) is the standard format required for clinical data submitted to the FDA.  Please consider adding support for these files via the SASxport package (https://github.com/warnes/SASxport) which supports reading and writing these files, including accessing and manipulating the SAS-specific features (variable labels, input formats, output formats, etc.) plus proper conversion to and from R factor objects.

**Comment by rogerjdeangelis** [comment]
Great package and I have used it many times, it does have some limitations

  1. Variable names have to be 8 characters or less
  2. Max char length is 200 bytes
  3. Label limited to 40 bytes
  4. Expensive converts and extracts  to and from IBM doubles to IEE 754
doubles

There are some alternatives

   The free WPS express edition 'proc R' does not limit the size of the
output SAS datasets from R or Python.
   Haven read.sas7bdat does not limit the size of the input SAS dataset

   https://www.worldprogramming.com/us/try-or-buy/wps/editions/express

   I used your SASXport to save long variable names in the SAS label and
provide a short SAS/WPS macro to rename generated 8 char names to long
variable names.


https://github.com/rogerjdeangelis/utl_R_sas_v5_xport_with_long_variable_names

   All of this will be mute when haven fixes the reamaining issues with
write.sas.

   Also maybe haven will consider V8 transport which does

**Comment by gwarnes-mdsol** [comment]
On Mon, Feb 26, 2018 at 11:40 AM Roger DeAngelis <notifications@github.com>
wrote:

> Great package and I have used it many times, it does have some limitations
>
> 1. Variable names have to be 8 characters or less
> 2. Max char length is 200 bytes
> 3. Label limited to 40 bytes
> 4. Expensive converts and extracts to and from IBM doubles to IEE 754
> doubles
>

These limitations are imposed by the file format itself[1], rather than the
package.   As stated in the original posting:

> The SAS transport format (.xport) is the standard format required for
> clinical data submitted to the FDA.

The primary purpose of this feature request is to enable users who must
(e.g. for FDA submissions) create or access these files to make use of the
`rio` package to do so conveniently.

The SASxport package does warn when a variable name is truncated, and I'll
add a feature enhancement request to ensure that warning occurs when
character variables and labels are truncated.

----

[1] SAS recently introduced a new 'v8' variant of the xport format that
resolves all but #4, and I will be extending the R SASxport package to
support the new format as time permits.



-- 
If this message is urgent please contact me via Hangouts or by phone:
585-678-6661.

**Comment by rogerjdeangelis** [comment]
Great news about V8 support.

You are right currently the FDA prefers V5 format and your package fills a
critical need for many clinical SAS programmers.

One downside of the WPS express edition(write.sas7bdat) is that the
sas7bdats are created outside of the R script.

**Comment by leeper** [comment]
This is already supported.

**Comment by gwarnes-mdsol** [comment]
Ah.  I wasn't aware that rio (via `haven` via `WizardMac/ReadStat`) supported `.xpt` files (v5 and v8!).
