### ISSUE TITLE
Set a limit of row to import?

### ISSUE THREAD

**Issue by joniarroba** [leeper/rio#176]
Please specify whether your issue is about:

 - [ ] a possible bug
 - [ X ] a question about package functionality
 - [ ] a suggested code or documentation change, improvement to the code, or feature request

Guys, is there a way in which I can define the total number of rows to import?  The use case is that some users have files that are way too big and before breaking the server, she/he could define to read only the first X initial rows. 

Any comments on this is very welcome.

**Comment by leeper** [comment]
Depends on the file type. If it's plain-text (CSV, TSV, etc.), the work is being done `data.table::fread()` so you can set the `nrows` argument. For most other formats, this isn't going to work.

**Comment by joniarroba** [comment]
Thanks, that already helps! Thanks for the prompt response!
