### ISSUE TITLE
Enhancement: allow folder paths and patterns in import_list

### ISSUE THREAD

**Issue by hughjonesd** [leeper/rio#181]
I've been looking for a way to import multiple files in one command. `import_list` does most of what I want. One enhancement would be to allow

```
import_list(folder, pattern = "*.csv", ...)
```

which is really just shorthand for `import_list(list.files(folder, full.names = TRUE, pattern = "*.csv"), ...)`, but would be nice and clear.

If you are open to this, I could provide a pull request.

**Comment by ruaridhw** [comment]
Implemented in #149 which was closed. Check out that PR for the discussion.

**Comment by hughjonesd** [comment]
Got it. Thanks.
-- 
Sent from Gmail Mobile
