### ISSUE TITLE
question: how to specify csv.gz format manually

### ISSUE THREAD

**Issue by rubenarslan** [leeper/rio#182]
I expected this to work

```
x <- rio::import("bla.csv.gzip0000_part_00.gz", "csv.gz")
```

But it gives me "format not supported". Just "csv" fails too (because rio applies `gzfile` only if format is missing).

After renaming, this works:

```
x <- rio::import("cycles.csv.gzip0000_part_00.csv.gz")
```

How do I specify gz'ed CSV format without renaming the file?

**Comment by leeper** [comment]
I don't think it's currently possible to do this without an explicit `.csv.gz` file extension.

**Comment by trevorld** [comment]
```
rio::import("bla.csv.gzip0000_part_00.gz", "csv", fread=FALSE)
```
 works for me.

**Comment by leeper** [comment]
Yea, this works for me so I'm closing as irreproducible. All of these should work:

```R
rio::export(mtcars, "mtcars.csv.gz")
rio::import("mtcars.csv.gz")
rio::import("mtcars.csv.gz", format = "csv")

rio::export(mtcars, "mtcars.gz", format = "csv")
rio::import("mtcars.gz")
rio::import("mtcars.gz", format = "csv")
```
