### ISSUE TITLE
Rio data.frame requirement?

### ISSUE THREAD

**Issue by shapenaji** [leeper/rio#183]
Thanks for the package!

This is a more general question about the data.frame requirement of the output of rio::import.

This makes it so that some rds files (which could contain anything) don't import. For example, I have a stanfit (https://cran.r-project.org/web/packages/rstan/vignettes/stanfit-objects.html) object stored in an RDS.

Is accessing other types of R objects in an RDS out-of-scope for rio::import?

**Comment by leeper** [comment]
Generally yes, but we should probably make an exception for RDS and Rdata files, given they can contain arbitrary R objects.

**Comment by leeper** [comment]
This is now implemented.
