### ISSUE TITLE
Unable to install Rcommander. Error while installing package “rio”. Error in readRDS(nsInfoFilePath) : error reading from connection

### ISSUE THREAD

**Issue by GaneshGitHubAccount** [leeper/rio#187]
Error while installing package "rio"

```R
## install package
install.packages("rio")

## Output 
Installing package into ‘/home/username/R/i686-pc-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/rio_0.5.10.tar.gz'
Content type 'application/x-gzip' length 70117 bytes (68 KB)
==================================================
downloaded 68 KB

* installing *source* package ‘rio’ ...
** package ‘rio’ successfully unpacked and MD5 sums checked
** R
** inst
** byte-compile and prepare package for lazy loading
Error in readRDS(nsInfoFilePath) : error reading from connection
ERROR: lazy loading failed for package ‘rio’
* removing ‘/home/username/R/i686-pc-linux-gnu-library/3.5/rio’

The downloaded source packages are in
	‘/tmp/Rtmp6v1Obt/downloaded_packages’
Warning message:
In install.packages("rio") :
  installation of package ‘rio’ had non-zero exit status

##Please help me to fix this issue. I am using ubuntu 16.04

**Comment by leeper** [comment]
Can you give me the output of `sessionInfo()`

**Comment by GaneshGitHubAccount** [comment]
Hi ,
The output of sessionInfo() is as follows : 
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: i686-pc-linux-gnu (32-bit)
Running under: Ubuntu 16.04.3 LTS
Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0
locale:
 [1] LC_CTYPE=en_IN       LC_NUMERIC=C         LC_TIME=en_IN       
 [4] LC_COLLATE=en_IN     LC_MONETARY=en_IN    LC_MESSAGES=en_IN   
 [7] LC_PAPER=en_IN       LC_NAME=C            LC_ADDRESS=C        
[10] LC_TELEPHONE=C       LC_MEASUREMENT=en_IN LC_IDENTIFICATION=C 
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
loaded via a namespace (and not attached):
[1] compiler_3.5.1 tools_3.5.1   
>

**Comment by leeper** [comment]
Some googling suggests it's probably an issue with one of the package dependencies.

Restart R using `R --vanilla` and do:

```R
utils::update.packages()
utils::install.packages("rio")
```

**Comment by GaneshGitHubAccount** [comment]
Tried your suggestion , but same error occurred.

**Comment by leeper** [comment]
Are you able to install other packages?

**Comment by GaneshGitHubAccount** [comment]
Yes , I installed other packages like curl , minqa , lme4 to name a few.

**Comment by leeper** [comment]
Unfortunately I have no idea what's causing this then. I've never seen this problem before.

**Comment by leeper** [comment]
Someone has suggested it could be a bad previous installation of rio. Can you try what is suggested here: https://stackoverflow.com/a/17448816/2338862
