### ISSUE TITLE
Use readxl?

### ISSUE THREAD

**Issue by leeper** [leeper/rio#19]
Another Hadley-verse package: https://github.com/hadley/readxl

**Comment by christophergandrud** [comment]
If this doesn't end up depending on rJava, which would be great.

**Comment by leeper** [comment]
The trade-off here is that readxl is read-only. So we if drop openxlsx for readxl, we lose the ability to write .xlsx files but gain the ability to read .xls files.

**Comment by christophergandrud** [comment]
It probably doesn't make sense to drop support for writing to .xlsx. I guess readxl could be added to just read.xls files. (would still need to depend on rJava, unfortunately).

**Comment by leeper** [comment]
@christophergandrud  I'm not seeing an rJava dependency? readxl looks like it's straight C/C++.

**Comment by christophergandrud** [comment]
Ah, sorry I was confusing it with the xlsx package

**Comment by leeper** [comment]
I'm leaning toward being able to read formats is more important than being able to write them, but I'm going to open an issue at readxl about writing to .xlsx. If he implements that, then we should obviously switch.

**Comment by chainsawriot** [comment]
Maybe, both? Best of both world. But it looks bloat.

**Comment by hadley** [comment]
What if you just suggested `openxslx` for writing? I think reading is a much more common use case, and readxl is quite a bit faster, so it seems worthwhile to use readxl there (esp. since it covers both xls and xlsx). Writing is less common, so requiring the user to install an extra package wouldn't be too bad.

**Comment by hadley** [comment]
It's also possible that `read_excel` might only need minor tweaks to work with ODS files, eliminating another package dep.

**Comment by leeper** [comment]
@hadley Thanks for this! I agree read is more important than write. I think if `read_excel` can do ODS, that would be a great addition and would definitely justify us switching away from openxslx for read.
