### ISSUE TITLE
Should rio return tibbles by default?

### ISSUE THREAD

**Issue by leeper** [leeper/rio#197]
Please specify whether your issue is about:

 - [x] a suggested code or documentation change, improvement to the code, or feature request

We've been returning data frames given that tibbles were (and have been) pretty unstable. Worth revisiting making tibbles the default output?

**Comment by nathancday** [comment]
Just for awareness the new .name_repair requirements/methods seem to be in flux https://github.com/tidyverse/tibble/issues/566 This is a pain point for an un-named columns that are being returned

**Comment by billdenney** [comment]
I'd prefer not.

With name repair, column names can be changed in ways that are not necessarily obvious to the user.  And, when I receive ugly data (sometimes with duplicate or NA names), tibbles will intentionally error.  I'd prefer to simply allow the user to use `as_tibble()` after the load, if that is what they want.

(For reference, I use tibbles a lot, but I prefer having the option.)
