### ISSUE TITLE
export() to *.xlsx with fill=NA?

### ISSUE THREAD

**Issue by modche** [leeper/rio#198]
- [ x] a suggested code or documentation change, improvement to the code, or feature request

Hi,

`rio`-package is really nice!

Is there a way to `export` a `tibble`to `*.xlsx`with filled `NA`-values for empty cells in the data_frame?

Michael

**Comment by leeper** [comment]
I'm not sure actually. I'll investigate. If you find a good solution, please consider a PR!

**Comment by nathancday** [comment]
If the columns are empty strings, "", looks like you would need to convert them to proper NA values firsts, perhaps with `dplyr::na_if()`. But once they are official R NAs you can pass the argument `keepNA = TRUE` to get NA representations written to Excel.

library(rio)
```
mtcars[1,] <- NA
mtcars %>% export("tst.xlsx")
mtcars %>% export("tst2.xlsx", keepNA = TRUE)
# see ?openxlsx::write.xlsx for more available arguments
```

**Comment by leeper** [comment]
I've added this as an example to `? export`, which seems sufficient at this point. Thanks, @nathancday!
