### ISSUE TITLE
Should import_list() work for JSON files?

### ISSUE THREAD

**Issue by nathancday** [leeper/rio#199]
This seems like a bug to me. The docs for `?import_list` say the return value should be a list, "If rbind=FALSE (the default), a list of a data frames. "

Here is a smol reprex.

``` r
list_obj <- split(iris, iris$Species)

str(list_obj, 1)
#> List of 3
#>  $ setosa    :'data.frame':  50 obs. of  5 variables:
#>  $ versicolor:'data.frame':  50 obs. of  5 variables:
#>  $ virginica :'data.frame':  50 obs. of  5 variables:

jsonlite::write_json(list_obj,"tst.json")

str(rio::import_list("tst.json"), 1)
#> List of 1
#>  $ :'data.frame':    5 obs. of  3 variables:

str(jsonlite::read_json("tst.json"), 1)
#> List of 3
#>  $ setosa    :List of 50
#>  $ versicolor:List of 50
#>  $ virginica :List of 50
```

<sup>Created on 2019-02-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

In building this out I found that `rio::export(list_obj, "tst2.json")` raises an error and think that may be related. The docs for `export` say "An exception to this is that x can be a list of data frames if the output file format is an Excel .xlsx workbook, .Rdata file, or HTML file. See examples.)" and my feeling is that JSON files should be included in these exceptions.

**Comment by leeper** [comment]
It's not a bug, it's just not supported for JSON.

**Comment by nathancday** [comment]
Would a PR to support JSON be welcome?

**Comment by leeper** [comment]
Definitely.

**Comment by nathancday** [comment]
I'm on it!

Thanks for this package, it is key piece of file IO in the boxR package, which is how I stumbled upon it. Happy to do my part to support.
