### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by leeper** [leeper/rio#2]
* [x] Update README (via a README.Rmd)
* [x] Add vignette
* [x] Document and add examples for `convert`
* [x] Update Maintainer in DESCRIPTION
* [x] Add inst/CITATION
* [x] Move inst/tests to tests/testthat

**Comment by leeper** [comment]
@chainsawriot Could you send a quick email to CRAN <cran@r-project.org> confirming that I'm taking over as maintainer on this?

**Comment by chainsawriot** [comment]
@leeper Done that.

**Comment by leeper** [comment]
@chainsawriot Many thanks!
