### ISSUE TITLE
export with append

### ISSUE THREAD

**Issue by julian-urbano** [leeper/rio#201]
When `export`ing a data.frame in CSV, one useful option is to append the contents to an existing file (eg. when processing in batches). In `data.table::fwrite` there is an argument `append` that does precisely this, of course omitting the column names when appending.

If we try this using `rio::export`, it doesn't work because `col.names` is always set to `TRUE` in `export_delim`.

```R
rio::export(iris[1:2,], "file.csv")
rio::export(iris[1:2,], "file.csv", append = TRUE)
```

```sh
$ cat file.csv
Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species
5.1,3.5,1.4,0.2,setosa
4.9,3,1.4,0.2,setosa
Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species
5.1,3.5,1.4,0.2,setosa
4.9,3,1.4,0.2,setosa
```

To solve this we need to manually set `col.names = FALSE`, but it should use the default in `fwrite` that writes the column names if the file does not exist, or omits if it does.

What do you think?

Thanks!

**Comment by leeper** [comment]
Good call. Want to send a PR (including a test)? Should be a pretty simple fix around here: https://github.com/leeper/rio/blob/master/R/export_methods.R#L5

**Comment by julian-urbano** [comment]
Sure, will do.

**Comment by leeper** [comment]
I just took care of this. Thanks for raising the issue!

**Comment by julian-urbano** [comment]
Hey, sorry I missed this. Thanks for the fix!
