### ISSUE TITLE
Variable Labels in Factorize and Characterize [Suggested Code Change]

### ISSUE THREAD

**Issue by davidaarmstrong** [leeper/rio#204]
Please specify whether your issue is about:
 - [x] a suggested code or documentation change, improvement to the code, or feature request

Would it be possible to change the `characterize` and `factorize` functions as follows?  This will propagate the variable label through to the newly created variable (if it exists).  

I also added a couple of lines to `factorize` that would omit missing values in the label table that identify original responses that were coded as missing.  

```R
characterize.default <- function(x, ...) {
    xlab <- NULL
    if(!is.null(attributes(x)$label)){
        xlab <- attributes(x)$label
    }
    
    if (!is.null(attributes(x)$labels)) {
        x <- as.character(factorize(x, ...))
        if(!is.null(xlab)){
            attr(x, "label") <- xlab
        }
        x
    } else {
        x
    }
}
```

and 

```R
factorize.default <- function(x, ...) {
    xlab <- NULL
    if(!is.null(attributes(x)$label)){
        xlab <- attributes(x)$label
    }
    if (!is.null(attributes(x)$labels)) {
        labs <- na.omit(attributes(x)$labels)
        x <- factor(x, labs, names(labs), ...)
        if(!is.null(xlab)){
            attr(x, "label") <- xlab
        }
        x
    } else {
        x
    }
    
}```

**Comment by leeper** [comment]
Can you show me a before and after on what the difference is in output?

**Comment by davidaarmstrong** [comment]
Here is the output from factorize in the current version:

> library(rio)
> dat <- import("https://quantoid.net/files/rbe/r_example.dta")
> fdat <- factorize(dat)
> str(dat)
'data.frame':   10 obs. of  3 variables:
 $ x1: num  1 2 3 4 3 4 1 2 5 6
  ..- attr(*, "label")= chr "First variable"
  ..- attr(*, "format.stata")= chr "%8.0g"
 $ x2: num  0 0 1 0 0 0 1 1 1 0
  ..- attr(*, "label")= chr "Second variable"
  ..- attr(*, "format.stata")= chr "%8.0g"
  ..- attr(*, "labels")= Named num  0 1
  .. ..- attr(*, "names")= chr  "none" "some"
 $ x3: chr  "yes" "no" "no" "yes" ...
  ..- attr(*, "label")= chr "Third variable"
  ..- attr(*, "format.stata")= chr "%3s"
> str(fdat)
'data.frame':   10 obs. of  3 variables:
 $ x1: num  1 2 3 4 3 4 1 2 5 6
  ..- attr(*, "label")= chr "First variable"
  ..- attr(*, "format.stata")= chr "%8.0g"
 $ x2: Factor w/ 2 levels "none","some": 1 1 2 1 1 1 2 2 2 1
 $ x3: chr  "yes" "no" "no" "yes" ...
  ..- attr(*, "label")= chr "Third variable"
  ..- attr(*, "format.stata")= chr "%3s"```

Note that the attributes, particularly the variable label on x2 (in this
case “Second Variable”) is not attached to x2 in the fdat data frame. With
the proposed change, you would get the following:

> dat <- import("https://quantoid.net/files/rbe/r_example.dta")
> fdat <- factorize(dat)
> str(dat)
'data.frame':   10 obs. of  3 variables:
 $ x1: num  1 2 3 4 3 4 1 2 5 6
  ..- attr(*, "label")= chr "First variable"
  ..- attr(*, "format.stata")= chr "%8.0g"
 $ x2: num  0 0 1 0 0 0 1 1 1 0
  ..- attr(*, "label")= chr "Second variable"
  ..- attr(*, "format.stata")= chr "%8.0g"
  ..- attr(*, "labels")= Named num  0 1
  .. ..- attr(*, "names")= chr  "none" "some"
 $ x3: chr  "yes" "no" "no" "yes" ...
  ..- attr(*, "label")= chr "Third variable"
  ..- attr(*, "format.stata")= chr "%3s"
> str(fdat)
'data.frame':   10 obs. of  3 variables:
 $ x1: num  1 2 3 4 3 4 1 2 5 6
  ..- attr(*, "label")= chr "First variable"
  ..- attr(*, "format.stata")= chr "%8.0g"
 $ x2: Factor w/ 2 levels "none","some": 1 1 2 1 1 1 2 2 2 1
  ..- attr(*, "label")= chr "Second variable"
 $ x3: chr  "yes" "no" "no" "yes" ...
  ..- attr(*, "label")= chr "Third variable"
  ..- attr(*, "format.stata")= chr "%3s"

Note that the variable label now follows x2 into the factorized data frame.
This is particularly useful when you will eventually want to export the
variable back to something like Stata or SPSS. In this case, the current
version of the function would only return the variable labels for the non
factors. The proposed change would return variable labels for all
variables.

Best, Dave.






Dave Armstrong
Canada Research Chair in Political Methodology
Associate Professor of Political Science
University of Western Ontario

w: http://quantoid.net


On May 15, 2019 at 11:46:37 AM, Thomas J. Leeper (notifications@github.com)
wrote:

Can you show me a before and after on what the difference is in output?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/leeper/rio/issues/204?email_source=notifications&email_token=ABD6OVOMGLIAKOBTZUTAC3DPVQV53A5CNFSM4HM4P332YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVPCYGI#issuecomment-492710937>,
or mute the thread

**Comment by leeper** [comment]
Got it. Thanks. Yes, this is a bug - appreciate the suggested fix!
