### ISSUE TITLE
col_names is rejected with ODS files

### ISSUE THREAD

**Issue by jllipatz** [leeper/rio#206]
When trying to read an ODS file with no header line containing column names, I get the following message :
formal argument "col_names" matched by multiple actual arguments

Example:
> library(readODS)
> write_ods(mtcars,"mtcars.ods")
  adding: content.xml (deflated 96%)
  adding: META-INF/ (stored 0%)
  adding: META-INF/manifest.xml (deflated 61%)
  adding: meta.xml (deflated 51%)
  adding: mimetype (deflated 4%)
  adding: styles.xml (deflated 70%)
> import("mtcars.ods",col_names=FALSE)
Error in readODS::read_ods(path = file, sheet = which, col_names = header,  : 
  formal argument "col_names" matched by multiple actual arguments
> read_ods("mtcars.ods",col_names=FALSE)
Parsed with column specification:
....

**Comment by chainsawriot** [comment]
There is an undocumented `header` argument for `rio::.import.rio_ods`, it will convert automatically into `col_names`. So, at the moment, you can try: `import('mtcars.ods', header = FALSE)`

Unfortunately, this argument is not documented. Probably because in the early days of rio, there was a need to unify all `header` / `col_names` arguments into `header`. It makes sense to remove that now.

@leeper

**Comment by chainsawriot** [comment]
related to #132 .

**Comment by jllipatz** [comment]
Is there a chance that the 'header' argument will disappear in some future? If so, the solution is not better than using read_ods instead of import!

**Comment by bokov** [comment]
#225 might fix this by mapping it same way that the `which` argument is mapped.

**Comment by leeper** [comment]
@bokov I think this is now fixed, right?

**Comment by bokov** [comment]
Yes! This is fixed (in addition, confirming that the `write_ods()` used in the original reprex gives the same outcome as `export()`).

```r
> export(mtcars,'mtcars1.ods')
  adding: content.xml (deflated 96%)
  adding: META-INF/ (stored 0%)
  adding: META-INF/manifest.xml (deflated 61%)
  adding: meta.xml (deflated 51%)
  adding: mimetype (deflated 4%)
  adding: styles.xml (deflated 70%)
> write_ods(mtcars,'mtcars2.ods')
  adding: content.xml (deflated 96%)
  adding: META-INF/ (stored 0%)
  adding: META-INF/manifest.xml (deflated 61%)
  adding: meta.xml (deflated 51%)
  adding: mimetype (deflated 4%)
  adding: styles.xml (deflated 70%)
> mt1 <- import('mtcars1.ods',col_names=F)
Parsed with column specification:
cols(
  A = col_character(),
  B = col_character(),
  C = col_character(),
  D = col_character(),
  E = col_character(),
  F = col_character(),
  G = col_character(),
  H = col_character(),
  I = col_character(),
  J = col_character(),
  K = col_character()
)
> mt2 <- import('mtcars2.ods',col_names=F)
Parsed with column specification:
cols(
  A = col_character(),
  B = col_character(),
  C = col_character(),
  D = col_character(),
  E = col_character(),
  F = col_character(),
  G = col_character(),
  H = col_character(),
  I = col_character(),
  J = col_character(),
  K = col_character()
)
> identical(mt1,mt2)
[1] TRUE

```

**Comment by leeper** [comment]
Super!
