### ISSUE TITLE
files with same names but different extensions

### ISSUE THREAD

**Issue by RawatVimal** [leeper/rio#208]
Please specify whether your issue is about:

 - [ ] a possible bug
 - [ ] a question about package functionality
 - [x] a suggested code or documentation change, improvement to the code, or feature request

import_list returns a named list with same name(w/o extension of file) for those files with same name.
This may create confusion as when you try to access elements of the named list by names it retuns only the first file.

**Comment by leeper** [comment]
Thanks! I'm going to add an `filename` attribute to every data frame. I'd change the names themselves but I'm worried people might be depending on the current names and don't want to break things. May revisit for a future release, though.
