### ISSUE TITLE
zip::zip() is deprecated

### ISSUE THREAD

**Issue by msberends** [leeper/rio#209]
Using `rio::export()` for an Excel file throws the following note, presumably from another package:

```
Note: zip::zip() is deprecated, please use zip::zipr() instead
```

This is the case on the latest CRAN version:

```r
packageVersion("rio")
#> [1] ‘0.5.16’
packageVersion("zip")
#> [1] ‘2.0.2’
```

**Comment by leeper** [comment]
Thanks! I'll investigate.

**Comment by leeper** [comment]
This one is beyond my control as it's not in the rio codebase.
