### ISSUE TITLE
Feature Request: Support for extracting tables from .docx files

### ISSUE THREAD

**Issue by billdenney** [leeper/rio#210]
I think that it would be helpful to support extracting tables from Microsoft Word .docx files via the docxtractr library (https://cran.r-project.org/web/packages/docxtractr/). Would you be interested in adding support to rio for that? (I'm happy to try to make the PR, if yes.)

This would be both an `import()` and `import_list()` method.

(I just learned how well you wrote the ability to add new formats, so it's easy to add this!  I may submit the PR today since I'm working on another PR.  If it's not of interest, no worries to ignore that PR.)

**Comment by leeper** [comment]
I'd lean toward mentioning it here: https://github.com/leeper/rio/blob/master/R/extensions.R#L23 for the time being

**Comment by leeper** [comment]
Thanks for the PR on this!
