### ISSUE TITLE
Feature request: support parquet

### ISSUE THREAD

**Issue by xiaodaigh** [leeper/rio#214]
Please specify whether your issue is about:

 - [ ] a possible bug
 - [ ] a question about package functionality
 - [X] a suggested code or documentation change, improvement to the code, or feature request

The [arrow package](https://cran.r-project.org/web/packages/arrow/index.html) now has native parquet read and write abilities.

**Comment by zjpi** [comment]
For easy reference `arrow::read_parquet` is the function
