### ISSUE TITLE
Using the same argument filters as #222 for .import.rio_rdata, .import.rio_xls, and .import.rio_ods

### ISSUE THREAD

**Issue by bokov** [leeper/rio#223]
Please specify whether your issue is about:

 - [ ] a possible bug
 - [ ] a question about package functionality
 - [x] a suggested code or documentation change, improvement to the code, or feature request

in #222, the `intersect()` and `setdiff()` functions were used to generically filter the arguments passed via `...` so that only the ones recognized by the underlying import function would get passed to it.

The functions `load()`, `readxl::read_xls()`, and `readODS::read_ods()` underlying `.import.rio_rdata()`, `.import.rio_xls()`, and `.import.rio_ods()` respectively have the same problem.

May I submit a PR/s implementing the same argument-filtering for those functions? If yes, do you prefer a separate PR for each, or grouped together?

**Comment by leeper** [comment]
Happy to have you tackle this! Your call on whether to submit separately or as one PR.

**Comment by bokov** [comment]
Went with separate, so it would be easier to review

**Comment by bokov** [comment]
These PRs are #225 for ODS, #229 for RData (and RDS), and #230 for XLS. Are there further corrections I should make?

Thanks.
