### ISSUE TITLE
What are the (near) universal arguments tabular import functions need?

### ISSUE THREAD

**Issue by bokov** [leeper/rio#228]
Please specify whether your issue is about:

 - [ ] a possible bug
 - [x] a question about package functionality
 - [ ] a suggested code or documentation change, improvement to the code, or feature request

If you are reporting (1) a bug or (2) a question about code, please supply:

This is more a design question to inform possible future code contributions rather than a question about existing functionality. It seems like the basic question is, "what arguments are so widely applicable to reading of tabular data that they should be standardized across all rio methods and mapped to the corresponding arguments of the underlying functions versus ones that are so function-specific that they should be passed via `...` (with dynamic filtering using `formals()` of the underlying import function).
 
I created and attached a spreadsheet of .import.rio_* formal arguments, with one row for each function, one column for each distinct argument name, and the data types of the arguments as the cell values. I colored the rarely used arguments green if I (kind of) understand why they make sense being implemented as they are. White means probably already consistent. Yellow means it might make sense to think about whether to make that argument standard to additional .import.rio_* functions or to remove it and let it get passed through `...`.

Take the colors with a grain of salt, I'm new to this project. Just thought seeing all the arguments lined up like this might be helpful.
[rio_import_concordance.xlsx](https://github.com/leeper/rio/files/3642884/rio_import_concordance.xlsx)

**Comment by leeper** [comment]
Let's move this conversation into #132, as it's the same
