### ISSUE TITLE
Handle HTTP Status Codes

### ISSUE THREAD

**Issue by leeper** [leeper/rio#23]
Try to fail gracefully on HTTP status code errors.

**Comment by leeper** [comment]
Works: 

```
import("http://www3.amherst.edu/~nhorton/precursors/files/2014-01.csv")
```

Doesn't work: 

```
import("https://github.com/ProjectMOSAIC/databases/raw/master/Data/2014-01.csv")
```

**Comment by christophergandrud** [comment]
Hu, I just tried both and they both worked. What error message do you get?

**Comment by leeper** [comment]
Hmm...they work for me now, too. This was an issue reported via email. I got a 503 error earlier, but now I can't reproduce it.

**Comment by christophergandrud** [comment]
Strange. Maybe the problem was with their connection?

**Comment by leeper** [comment]
Yea, I tried again and cannot reproduce it now, so I'm closing.
