### ISSUE TITLE
Even lazier idea for a MS Office and LibreOffice sniffing function.

### ISSUE THREAD

**Issue by bokov** [leeper/rio#237]
Please specify whether your issue is about:

 - [ ] a possible bug
 - [ ] a question about package functionality
 - [x] a suggested code or documentation change, improvement to the code, or **feature request**

I often am given MS Office files that have missing extensions or incorrect ones (e.g. a novice user tried to 'convert' them to csv by renaming them). Not only are these zip files, they can have the same file signature as LibreOffice files and who knows what else.

This is a function that scans for files that are specific to MS Office and LibreOffice/OpenOffice.

As with #236, my question is: would this function be useful to contribute to rio, for example to augment the current extension-only dispatch of `readxl` and `readODS` methods.

Put your code here:

```R
isfilezipdoc <- function(filename, 
                                     docpaths=c(MSO='[Content_Types].xml',
                                                         OO='META-INF/manifest.xml'), tf=TRUE){
    matchedpaths <- docpaths %in% unzip(filename,list=TRUE)[,1] 
    if(tf) return(any(matchedpaths))
    return(names(docpaths[matchedpaths])) 
}
```

**Comment by bokov** [comment]
Note: as written it cannot distinguish between .xlsx vs .docx vs .pptx nor between the various LibreOffice equivalents, though it can tell them from each other. This should be okay though because `rio` only supports the spreadsheet file types from those respective office suites, right?

**Comment by leeper** [comment]
I'm not sure it's that useful because these are pretty unambiguous file extensions?

**Comment by leeper** [comment]
Gonna close this.
