### ISSUE TITLE
Support for .mat files

### ISSUE THREAD

**Issue by currymj** [leeper/rio#24]
The package R.matlab makes it really easy to add support for reading/writing .mat files (it took one added line to get import working; I have this done if a PR is wanted). However, a .mat file can in general include lots of matrices and other objects, so R.matlab returns a named list of every object contained in the file. I'm not sure if this breaks the desired interface for rio -- that it should always return a data.frame or something like it. It also seems like it would complicate conversion.

Is it worth adding in spite of possible inconsistency?

**Comment by leeper** [comment]
Hmm...sounds potentially useful but I see two concerns: (1) I think it's important that the response is type consistent (i.e., a data.frame), and (2) importing R.matlab adds a lot of dependencies. If you send a pull request, I'll take a look. But I'm not sure if it makes sense to include at this point.

**Comment by currymj** [comment]
In my experience with .mat files they almost always have more than one object in them. So I don't see a way to do this while keeping the interface consistent. Either the return type would have to be inconsistent, or the import function would have to demand the name of the object to import as an additional argument whenever it sees a .mat file extension.

It might be helpful to print a message pointing someone to R.matlab if they try to import a .mat file, but I think you're right that integrating it probably wouldn't make sense.

**Comment by leeper** [comment]
As of https://github.com/leeper/rio/commit/f115d46b8046beaa119bb274052c19e7b39e0991, I've added a hopefully informative error message when attempting to import from or export to matlab files, which points users to `R.matlab::readMat` and `R.matlab::writeMat`.
