### ISSUE TITLE
rio::export() is throwing an error when exporting a zipped file

### ISSUE THREAD

**Issue by ashirwad** [leeper/rio#254]
Please specify whether your issue is about:

 - [x] a possible bug
 - [ ] a question about package functionality
 - [ ] a suggested code or documentation change, improvement to the code, or feature request

If you are reporting (1) a bug or (2) a question about code, please supply:

 - [a fully reproducible example](http://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) using a publicly available dataset (or provide your data)
 - if an error is occurring, include the output of `traceback()` run immediately after the error occurs
 - the output of `sessionInfo()`

Put your code here:

``` r
library(rio)
export(mtcars, "mtcars.csv.zip")
#> Warning in system2(zip, args, input = input, invisible = TRUE): '"zip"' not
#> found
#> Error in compress_out(cfile = cfile, filename = file, type = compress): File compression failed for mtcars.csv.zip!
traceback()
#> No traceback available
sessionInfo()
#> R version 3.6.1 (2019-07-05)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 17134)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.1252 
#> [2] LC_CTYPE=English_United States.1252   
#> [3] LC_MONETARY=English_United States.1252
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] rio_0.5.16
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.2        knitr_1.24        magrittr_1.5     
#>  [4] hms_0.5.1         rlang_0.4.0       stringr_1.4.0    
#>  [7] highr_0.8         tools_3.6.1       data.table_1.12.2
#> [10] xfun_0.9          htmltools_0.3.6   readxl_1.3.1     
#> [13] yaml_2.2.0        digest_0.6.20     tibble_2.1.3     
#> [16] crayon_1.3.4      zip_2.0.4         vctrs_0.2.0      
#> [19] curl_4.0          zeallot_0.1.0     evaluate_0.14    
#> [22] haven_2.1.1       rmarkdown_1.15    openxlsx_4.1.0.1 
#> [25] stringi_1.4.3     cellranger_1.1.0  compiler_3.6.1   
#> [28] pillar_1.4.2      forcats_0.4.0     backports_1.1.4  
#> [31] foreign_0.8-71    pkgconfig_2.0.2
```
<sup>Created on 2019-12-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by leeper** [comment]
You don't have a zip compression utility on your computer, or it's not available on the system path. You can install Rtools (https://cran.r-project.org/bin/windows/Rtools/) to obtain one, or use another zip command line tool of your choice.

**Comment by ashirwad** [comment]
You are right! I installed Rtools and the problem is now fixed. :) Also, thanks for this awesome package.
