### ISSUE TITLE
Implement preview mode?

### ISSUE THREAD

**Issue by leeper** [leeper/rio#26]
Stata and Excel both offer interactive file import functionality that allows one to dynamically modify delimiters and confirm import. A simple version of this for rio would show the imported data.frame before returning it.

This is what the Stata interface looks like: http://www.stata.com/stata13/importing-and-exporting-text-delimited-data/

**Comment by chainsawriot** [comment]
A simple head(x) before returning x in import will do the job?

**Comment by leeper** [comment]
@chainsawriot That's a much simpler alternative!

**Comment by leeper** [comment]
My vision for this is really an interactive interface, which would require a tcl/tk dependency. As such, I'm going to close this and #29. Perhaps it's something that can be created as a separate package.
