### ISSUE TITLE
Consider the possibility to include "vroom" among the supported functions

### ISSUE THREAD

**Issue by AndreaPi** [leeper/rio#270]
my issue is about:

 - [x] a suggested code or documentation change, improvement to the code, or feature request

Hi!

First of all, let me thank you for `rio`! It's an amazing package which helped me so much in the past years, making I/O access in R faster, simpler and more transparent across platform. I recently learned about the [`vroom`](https://cran.r-project.org/web/packages/vroom/index.html) package, by Jim Hester, Hadley Wickham and others. Its goal is to read delimited files (CSV, TSV, etc.). `rio` already provides capabilities for that, but I got curious about `vroom` because it can use Altrep (in R 3.5+) and it promises speedups even with respect to a strong benchmark such as `data.table::fread`:

https://cran.r-project.org/web/packages/vroom/vignettes/benchmarks.html

Would you consider adding `vroom` to the list of tools used by `rio`? Thanks!

**Comment by leeper** [comment]
I think we'll stick with data.table for now; if vroom really takes off, we can investigate more.

**Comment by AndreaPi** [comment]
NP, I'll close the issue then. For various reasons, I'm not using R much anymore (but if I'll be back, I'll start using `rio` again! 🙂)

**Comment by tanchangde** [comment]
> I think we'll stick with data.table for now; if vroom really takes off, we can investigate more.

[Vroom Benchmarks](https://cran.r-project.org/web/packages/vroom/vignettes/benchmarks.html)
