### ISSUE TITLE
trouble opening the package

### ISSUE THREAD

**Issue by Anton2417** [leeper/rio#274]
Please specify whether your issue is about:

 - [ 1] a possible bug
 - [ ] a question about package functionality
 - [ ] a suggested code or documentation change, improvement to the code, or feature request

If you are reporting (1) a bug or (2) a question about code, please supply:

 - [a fully reproducible example](http://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) using a publicly available dataset (or provide your data)
 - if an error is occurring, include the output of `traceback()` run immediately after the error occurs
 - the output of `sessionInfo()`

Put your code here:
> library(rio)
Error: package or namespace load failed for ‘rio’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘zip’
> traceback()
6: stop(msg, call. = FALSE, domain = NA)
5: value[[3L]](cond)
4: tryCatchOne(expr, names, parentenv, handlers[[1L]])
3: tryCatchList(expr, classes, parentenv, handlers)
2: tryCatch({
       attr(package, "LibPath") <- which.lib.loc
       ns <- loadNamespace(package, lib.loc)
       env <- attachNamespace(ns, pos = pos, deps, exclude, include.only)
   }, error = function(e) {
       P <- if (!is.null(cc <- conditionCall(e))) 
           paste(" in", deparse(cc)[1L])
       else ""
       msg <- gettextf("package or namespace load failed for %s%s:\n %s", 
           sQuote(package), P, conditionMessage(e))
       if (logical.return) 
           message(paste("Error:", msg), domain = NA)
       else stop(msg, call. = FALSE, domain = NA)
   })
1: library(rio)
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] tools     stats     graphics  grDevices utils     datasets  methods  
[8] base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5        crayon_1.3.4      lifecycle_0.2.0  
 [4] magrittr_1.5      pillar_1.4.6      stringi_1.4.6    
 [7] rlang_0.4.7       curl_4.3          rstudioapi_0.11  
[10] data.table_1.13.0 vctrs_0.3.2       ellipsis_0.3.1   
[13] forcats_0.5.0     foreign_0.8-80    tinytex_0.25     
[16] hms_0.5.3         xfun_0.16         compiler_4.0.2   
[19] pkgconfig_2.0.3   haven_2.3.1       tibble_3.0.3 
```

**Comment by bokov** [comment]
Have you tried installing the package `zip` via, e.g. `install.packages('zip')`?
