### ISSUE TITLE
qt4 issue in ubuntu 20.04

### ISSUE THREAD

**Issue by alatop007** [leeper/rio#276]
Hello there,

I have an issue installing rio on Ubuntu 20.04

Based on my research, I think it has to do with qt4 been dropped by ubuntu in 20.04 version. 

Maybe a modification is required for rio to be compatible with qt5.

Can you kindly advise on how to go about this issue?

Thanks

**Comment by chainsawriot** [comment]
I am using Ubuntu 20.04. No problem installing the package. Also, none of the rio's dependencies needs qt4 (AFAIK).
Could you please copy and paste the error message here? 
Thank you very much.

**Comment by bokov** [comment]
Same here-- no problems installing rio in 20.04

**Comment by leeper** [comment]
Closing for now
