### ISSUE TITLE
Turning character variables into factors with factorize. 

### ISSUE THREAD

**Issue by davidaarmstrong** [leeper/rio#278]
- [x] a suggested code or documentation change, improvement to the code, or feature request

I am wondering whether there is a good argument to be made for being able to turn character variables into factors automatically with `factorize()`.  I understand that one might not want that to be the default behaviour, but it would be nice to have that option.  I'm envisioning something like the following: 

```R
## load package
library("rio")
dat <- tibble(
  x_chr = c("one", "two", "three"), 
  x_fac = factor(1:3, labels=c("a", "b", "c"))
)

dat_fac <- factorize(dat, convert_characters=TRUE)

dat_fac
# # A tibble: 3 x 2
#   x_chr x_fac
#   <fct> <fct>
# 1 one   a    
# 2 two   b    
# 3 three c
```

as opposed to what would currently happen which is that `x_chr` would remain a `chr` type variable.

**Comment by leeper** [comment]
done
