### ISSUE TITLE
Unable to load 'Rio': " [] declared in NAMESPACE but not found "

### ISSUE THREAD

**Issue by miaase** [leeper/rio#281]
Hi guys,

I am a new user in 'R', but I know Stata well.

I try to install and load packages to get started, but I encounter a problem with 'Rio' as I try to load it via Pacman.  

I run the following command:
install.packages("pacman")
require(pacman)  # Gives a confirmation message.
library(pacman)  # No message.

pacman::p_load(pacman, dplyr, GGally, ggplot2, ggthemes, 
               ggvis, httr, lubridate, plotly, rio, rmarkdown, shiny, 
               stringr, tidyr) 

I get this back in the console:

rio installed
Advarselsbeskeder:
1: S3 methods ‘names<-.Workbook’, ‘getNamedRegions.Workbook’, ‘getNamedRegions.default’, ‘names.Workbook’, ‘read.xlsx.Workbook’, ‘read.xlsx.default’ were declared in NAMESPACE but not found 
2: I pacman::p_load(pacman, dplyr, GGally, ggplot2, ggthemes, ggvis,  :
  Failed to install/load:
rio

Here is the first info from the sessioninfo:
> sessionInfo()
R version 4.0.4 (2021-02-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Hope you can help me go along!

Best,
Michael Seeberg

**Comment by leeper** [comment]
Can you try just installing using `install.packages("rio")` ?

**Comment by miaase** [comment]
Thomas - thanks so much for getting back to me. 

I've tried to just install Rio, tried to update packages using update.packages() and update.packages('rio'). I have tried to uninstall R and RStudio, and tried to make a new directory on my laptop to make full re-installation. 

My gist is that there is som things going on with the access to folders but I cannot get my head around it.  

Let me know if you have any other good advices!

Best, 
Michael

Ps. I was just together with Henrik and Merete and should say hi to you ;-)

**Comment by bokov** [comment]
Try posting the actual error output from `install.packages()` and the full output from `sessionInfo()`. Since we cannot reproduce the problem on our own computers, the only way we are able to help is to have as much detail as possible about what is happening on yours.

Or, you can try opening a `cmd` shell, creating an empty directory and `cd` ing to it, and launching bare-bones R like this:
`R --vanilla`
Then, run `install.packages("rio")` from that R session.

Or, you can  try getting a free account on https://rstudio.cloud/

Then, try doing `install.packages("rio")` there. Does it work in that vanilla environment?

**Comment by Niwa-Tech** [comment]
Hi 
I'm a beginner to R and Me too have the same problem. When I'm trying to install 'rio' i get the below. Can any one help me to solve this. Version use : version.string R version 3.6.1 (2019-07-05)

_install.packages("rio")
Warning in install.packages :
  dependency ‘foreign’ is not available

  There is a binary version available but the source version is later:
    binary source needs_compilation
rio 0.5.26 0.5.29             FALSE

installing the source package ‘rio’

trying URL 'https://cran.rstudio.com/src/contrib/rio_0.5.29.tar.gz'
Content type 'application/x-gzip' length 445401 bytes (434 KB)
downloaded 434 KB

ERROR: dependency 'foreign' is not available for package 'rio'
* removing 'C:/Users/Niwarthana/anaconda3/envs/rstudio/lib/R/library/rio'
Warning in install.packages :
  installation of package ‘rio’ had non-zero exit status_

**Comment by miaase** [comment]
Hi,
I ran 'Rstudio' as administrator (right click on program-ikon). That solved issues for me. Hope it'll work for you as well!

Best, 
Michael
