### ISSUE TITLE
CRAN release

### ISSUE THREAD

**Issue by ycphs** [leeper/rio#286]
The last release is 3 years old. It would be great if the updates are released to CRAN.

Let me know if you need support.

**Comment by rolweber** [comment]
On CRAN, I see version 0.5.27 from 2021-06-21 (after you opened this issue) and 0.5.26 from 2021-03-01. The last release before that was indeed in 2018.

The last tag in this repo is 0.5.10 though. Current tags are created in a different repo: https://github.com/cran/rio/tags
