### ISSUE TITLE
Use fastread (or fread)

### ISSUE THREAD

**Issue by leeper** [leeper/rio#3]
Consider `fastread::read_delim` and `fastread::read_csv` or faster import (but note changed settings).

`datatable::fread` can also return a data.frame, so that's an option.

**Comment by christophergandrud** [comment]
This might be clunky, but would it make sense to use `fread` (or fastread) by default and add an argument allowing users to switch to a more traditional method (e.g. `read.table`) if they want to? Or vice versa?

**Comment by leeper** [comment]
Yes, I think this should get switched over to `fastread` and then `import` can take an optional argument `fastread` (default is `fastread = TRUE`) that can be set to `FALSE` to use `read.table`, `read.delim`, `read.csv`, or `read.fwf` instead.

**Comment by christophergandrud** [comment]
I like that idea. Note that Hadley is planning on changing the name for **fastread**: https://github.com/hadley/fastread/issues/58.

**Comment by leeper** [comment]
I've added this as a separate branch, given that fastread is not yet on CRAN.

**Comment by christophergandrud** [comment]
That's a good idea. fastread still has a fair number of kinks to work out. I'll test this branch though.

**Comment by leeper** [comment]
It's also kind of verbose, but I've asked if we can make that optional (https://github.com/hadley/fastread/issues/59).

**Comment by dpastoor** [comment]
one other option would be to use data.table(fread()) 'for now' then as fastread matures decide if you'd want to replace. Their api's are similar enough that it likely could be reasonably gracefully switched over if necessary.

The solution I've found is just to use a try on fread then fall back to read.delim/read.table if it errors then finally error completely if neither works. This way for some of the edge cases that fread doesn't do (such as multiple whitespace) it can still be read in, but will default to fread in all cases that it works.

**Comment by leeper** [comment]
@dpastoor Want to send a pull request that tries that out? I'll add it as another branch that we can test out.

**Comment by dpastoor** [comment]
sure I'll give it a shot

**Comment by christophergandrud** [comment]
In these pre-release days this isn't really a problem, but one thing to consider about using `fread` then switching to `fastread` if done after wide release is that there are a lot of possibilities to break code. I imagine that the data frames created from each will be different, perhaps in hard to anticipate ways.

**Comment by leeper** [comment]
Good point, @christophergandrud. I'm not really sure how we would decide which one is better. There's certainly something to be said for using `fread` because it's more mature, but whatever we choose should probably be a permanent decision.

**Comment by christophergandrud** [comment]
I agree. Maybe it's good to think of what criteria the choice should be made on. Speed is an obvious one. Probably need to think more about features of the output (and how closely they conform to data frames that result from functions used for data in formats fread/fastread don't handle). 

Consistency is definitely a virtue with this function.

**Comment by leeper** [comment]
Yes, I actually think it might be worth setting up some tests for each
input and output function to make sure that regardless of format rio gives
more or less the same data structure. Some of the import functions, for
example, are vague about factor variables...I'd like to make the whole
package `stringsAsFactors = FALSE` but that might actually require
post-processing some of the data.frames for underlying import functions
that do not have an explicit option for that.

PS. I gave you write access to the repo, so feel free to make changes as
you see fit.

**Comment by christophergandrud** [comment]
Great. Completely agree on these tests (and `stringsAsFactors`). I'll start using rio in my own work--often the best way to find bugs/oddities.

**Comment by dpastoor** [comment]
I think the best argument to fread is that it is mature now. Hadley et al are some of the most prolific people I've ever seen, but I just don't see maturing fastread as a pressing issue in comparison to the other packages at the moment. If it came to a point where fastread was adding functionality well beyond that of fread you could always just release a new major version and push to document changes as best a possible. I don't think the api would change `that much`. As of now it is things like `header = T/F` for both read.x and fread but it is `col_names= T/F` for read_x 

I'll try to get to that pull request in the next day or two. I actually envision it as a 'try_fread' function that can actually handle by default tab/space/comma delim values and if fails then fall back on the default reader and return the fread error in case people want to track down what the issue is.

So far the only thing I've seen fread stumble on consistently is variable whitespace delims.

**Comment by leeper** [comment]
@dpastoor Sounds great. I like the usage of `try`. I think it would actually be great if we could make that package-wide and try to intelligently handle failures when the file isn't actually of the type implied by the file extension.

**Comment by leeper** [comment]
Hadley renamed **fastread** to **readr** and quieted a lot of the messages. Will need to update this, accordingly.

**Comment by christophergandrud** [comment]
Based on the comparison to `fread` on the **readr** README, it seems like just going with `fread` makes more sense for **rio**.

**Comment by leeper** [comment]
I think I agree, if for speed alone. Let's do that, but return a data.frame by default (with an option to return a data.table).

**Comment by christophergandrud** [comment]
Sounds good to me.

**Comment by leeper** [comment]
I added this on a separate branch. I think it needs some testing before merging into master.

**Comment by christophergandrud** [comment]
Great. I installed the branch and will begin using it/report bugs I encounter.

**Comment by leeper** [comment]
Here's another package to keep on the radar (it's on CRAN, too): https://github.com/jabiru/csvread

**Comment by leeper** [comment]
I've merged the **fread** branch into **master**, so I'm closing this ticket. Report any new problems that emerge as a new ticket.

**Comment by hadley** [comment]
I'd argue that you should make readr the default, and use `data.table::fread` as an optional extra:

* Yes, data.table fread will always be faster, but this won't make much of a practical difference until you open files that are hundreds of megabytes (which most people don't have).

* readr is consistent with haven and readxl. You'll always get the same of sort of data frame back: no row names, un-munged column names, no factors, classed with tbl_df. 

* readr can parse date-time variables to yield POSIXct.

* readr _is_ under active development.

**Comment by dpastoor** [comment]
> readr is under active development.

to be fair, as of posting that comment it was still `fastread` and you hadn't started commiting your huge overhaul (publicly) :-)

Given added benefits of the past couple weeks as `readr` has matured, I will also give another +1 to reconsider readr, as it also gives a lot of flexibility with some of the additions eg. `read_lines()` etc, but as hadley mentioned, the standardization of the sort of dataframe that comes back is IMO more important than 'pure' speed in the majority of users cases.

**Comment by markdanese** [comment]
Just to be clear on my [closed issue](https://github.com/leeper/rio/issues/48), the suggestion was for **fixed width files only.**  These are files that have no delimiter and are indexed by location (i.e., age might be a 3 digit variable in fields 4-6).  For that, `readr::read_fwf()` works really well (see my github post referenced in the closed issue).  `fread()` does not handle those.

[I prefer `fread()` for most other file reading tasks.  We have tested it internally, and it is consistently much faster (more than 2x on the multi-gigabyte files we work with).]

**Comment by bwiernik** [comment]
Would it be possible to add an argument to use `readr` over `fread`? I'm specifically wishing to avoid issues with `fread` mangling date-time variables.

**Comment by leeper** [comment]
It's not possible.
