### ISSUE TITLE
Shiny frontend?

### ISSUE THREAD

**Issue by vnijs** [leeper/rio#31]
Great work on Rio. Are you interested in having a Shiny frontend for Rio? If so, chunks of the code I have for the Data and View (and perhaps Transform) tabs in my app may interest you.

App: https://vnijs.shinyapps.io/base
Code: https://github.com/vnijs/radiant/tree/master/inst/base/tools/data

**Comment by leeper** [comment]
I don't think this should be a part of the core package. My general view on Shiny is that there should be packages and then Shiny wrappers for those packages separately so that a package doesn't have dependencies that some users (and some platforms) might never make use of.

**Comment by christophergandrud** [comment]
[shinyStan](https://github.com/stan-dev/shinystan) is a good model to emulate in this regard.

**Comment by vnijs** [comment]
Makes sense. Had not seen shinyStan before. Thanks for the link.
