### ISSUE TITLE
Better format inference for URL redirects

### ISSUE THREAD

**Issue by leeper** [leeper/rio#36]
URL redirects currently require explicit use of the `format` argument ([for example](https://twitter.com/thosjleeper/status/598396704807870465)).

Development version of curl should allow MIME-type inspection (`curl_fetch_disk()`) per [this tweet](https://twitter.com/hadleywickham/status/598503787687387136).

Perhaps alternatively we can capture the file extension from the eventual URL that is being redirected to.

**Comment by christophergandrud** [comment]
That is a great idea.

**Comment by leeper** [comment]
[Correlates of War](http://www.correlatesofwar.org/data-sets/folder_listing) will be good examples of this as they involve redirects where file format is only included as a MIME type.

**Comment by leeper** [comment]
Code [here](https://github.com/leeper/rio/blob/master/R/import.R#L139) should be something like this:

```R
h <- curl::parse_headers(u$headers)
m <- strsplit(h[grep("Content-Type", h)], ": ")[[1]][2]
format <- mime::mimemap[grep(m, mime::mimemap)]
```

But `mimemap` is perhaps not complete. For example, `"text/comma-separated-values"` does not exist, only `"text/csv"`. Same thing for `"text/tab-separated-values"`. And it doesn't include the usual binary formats (Stata, SPSS, etc.).

Another option is to look at the `Content-Disposition` header:

```R
h <- curl::parse_headers(u$headers)
d <- strsplit(h[grep("Content-Disposition", h)], ": ")[[1]][2]
if(grepl("filename", d)) {
    d <- gsub("filename=", "", regmatches(d, regexpr("filename=(.+?)$", d)))
    f <- basename(gsub("[\"\']", "", d))
    format <- get_ext(f)
} else {
   # fail gracefully
}
```
