### ISSUE TITLE
Optionally zap_labels for haven imports

### ISSUE THREAD

**Issue by leeper** [leeper/rio#37]
haven will return "labelled" class columns. We can use `zap_labels()` (specifically, [`df[] <- lapply(df, zap_labels)`](https://github.com/hadley/haven/issues/56#issuecomment-90740523)) to eliminate them.

**Comment by izahn** [comment]
I think this is badly needed, and I would argue this should be the default. Those labels are too fragile and tend to mess things up. IMO this really needs to be solved in haven, but a look at the issues over there suggests there is little interest in changing the way haven imports labels. If you do add something like this please keep an eye out for https://github.com/hadley/haven/issues/105.

I would also like to see this go one step further along the lines of
```
attr(df, "labels") <- list(variables = sapply(df, attr, which = "label"),
                          values = sapply(df, attr, which = "labels"))
df[] <- lapply(df, zap_labels)
df[] <- lapply(df, function(x) {attr(x, "label") <- NULL; return(x)})
```

**Comment by leeper** [comment]
@izahn I agree this should probably be the default. I don't have time to implement at the moment, but if you send a pull request, I'll gladly accept.

**Comment by izahn** [comment]
OK great, I will prepare a pull request in the next day or two.

**Comment by izahn** [comment]
Sorry for the delay. I tried raising the issue with the haven folks (https://github.com/hadley/haven/issues/106), since this really should be solved there. Since I received no response I guess cleaning it up in rio makes sense. 

I've made a first pass at this in https://github.com/leeper/rio/pull/49. I've only cleaned up stata import so far, but if the change seems acceptable there I will give similar treatment to `import.sav` and any other functions using haven.

**Comment by leeper** [comment]
In principle it looks good. I'll try to take a thorough look later today and let you know if we should make changes.

**Comment by izahn** [comment]
I've opened a new PR that I think addresses this satisfactorily (https://github.com/leeper/rio/pull/50). I have a limited number of data files to test it on, but it works on everything I've tried.

**Comment by leeper** [comment]
Great! I'll take a look. Reminds me that we need a test suite of files.

**Comment by leeper** [comment]
This is now merged. I'm going to add some testing and make sure everything works alright, but I'll close this as merged now. Thanks so much!
