### ISSUE TITLE
Support for databases using dplyr src_* functions.

### ISSUE THREAD

**Issue by jsonbecker** [leeper/rio#43]
`dplyr` has great functions for reading and writing to databases. Adding `import.postgresql`/`export.postgresql` and `import.mysql`/`export.mysql` could greatly expand the foot print of available sources.

Some considerations;

* Because of the required arguments such as `dbname`, `username`, `password`, `host`, and `port`, this may be well-suited to a class that can validated that a minimum set of arguments are supplied.
* Should include options to specify a `table` since this package expects to return a single `data.frame` like object (`dt` or `tbl_df` or `data.frame`)  or write from a single object.
* Copy to memory can be an option set to `TRUE` by default.

**Comment by leeper** [comment]
I like this a lot. I'm thinking this should be fairly easy to implement actually. We should be able to do something like: 

```R
import.db <- function(db, table, ...) {
  DBI::dbReadTable(conn = db, name = table, ...)
}
export.db <- function(x, db, table, ...) {
    DBI::dbWriteTable(conn = db, name = if (!missing(table)) table else as.character(substitute(x)), value = x, ...)
}
```

But, I'll need to generalize this a bit so that it can actually initialize databases in some kind of intelligent way (for `export.db`) and so that it can create a database connection object, if needed, for `import.db` (something like `con <- dbConnect(RSQLite::SQLite(), ":memory:")`).

**Comment by jsonbecker** [comment]
If you're willing to import dplyr, it could be a switch on various src_ back ends that call the tbl() function.

I worry a little about using DBI directly since that requires users to know more about drivers. The other option is with a "type" argument plus switch, we could attempt to install a choice R package like RPostgreSQL and then just call dbReadTable/dbWriteTable from that back end, this way some of the driver constraints are gone.

An advantage of dplyr src functions is the common interface to connection information, but non-RJDBC/RODBC connections are fairly consistent anyway. dplyr also has build_sql which might be nice for escaping queries if they were to be parameterized and offered so that whole table fetch was not the only option.

**Comment by leeper** [comment]
We definitely want to keep the interface as simple as possible, so I'm open to a dplyr import if that keeps things easier. I'm trying to envision what argument we would want to expose for the user: do they need to create a database connection and feed that to `import()`, or do we want them to be able, e.g., just feed a file name of say an sqlite database, and have `import()` handle all of the overhead?

Probably the latter, but then we need to identify the set of databases worth supporting. And sqlite is the only thing that is going to work out-of-the-box on all platforms, right?

**Comment by jsonbecker** [comment]
I think that `dplyr` imports the necessary drivers for cross platform support of MySQL and PostgreSQL in addition to SQLite.

You can do something like:

```r
import.db <- function(db_type, table, ...){
  switch(db_type,
             mysql = collect(tbl(src_mysql(dbname, host, port, username, password, ...), from = table)
             postgresql = ...,
             sqlite = ...)
}
```

I might personally prefer to have an `import.db_type` for each database type because there are some specifics. Plus, I think it'd be worth offering lazy options so that it isn't always collected.

**Comment by jsonbecker** [comment]
What's nice about using the `dplyr::src_*` functions is it takes care of silently looking for packages like `RMySQL` etc. This way the dependency management is good and handled by smarter people than us when ti comes to DB drivers. And I'd expect it'd be easy enough actually to just call to `paste0('src_', db_type)` at some point and even further generalized here so that any new backend supported by `dplyr` is easily supported here.

**Comment by leeper** [comment]
Yes, this looks like a reasonable approach. Feel free to write further ideas here, or send a pull request. I'm hoping to work on this later in the week.

**Comment by leeper** [comment]
I'm closing this for now. Given that we're creating an extension mechanism (through the `.import()` and `.export()` methods), I think database handling could be a separate package that simply adds new methods. There's an obvious use for it - import from a wide array of database types using a single, simplified interface - but it adds a lot of dependencies that aren't essential for rio.

**Comment by jsonbecker** [comment]
I agree. The additional arguments needed as well fall a bit outside of the clean interface here. The one example might be `sqlite` since that's really designed to have the data passed around as a single file, much like the other data types already in `rio`.
