### ISSUE TITLE
import from URL timeout

### ISSUE THREAD

**Issue by christophergandrud** [leeper/rio#46]
```{R}
URL <- 'https://raw.githubusercontent.com/christophergandrud/EIUCrisesMeasure/master/data/results_kpca_rescaled.csv'
index <- rio::import(URL)
```

Results in:

```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
```

Issue began with upgrade to R 3.2.2. I've run using the internal code and it seems to work fine.

**Comment by leeper** [comment]
Can't replicate this now. Closing for the time being. Feel free to reopen if it re-emerges, @christophergandrud.
