### ISSUE TITLE
Support for HTML, XML, png, jpeg?

### ISSUE THREAD

**Issue by brendan-R** [leeper/rio#55]
Firstly, thanks for rio!

I'm currently switching the internals of [`boxr`](https://github.com/brendan-r/boxr) to use it to translate between files and R objects. Previously, I was using the defaults built in to `httr`'s `content` function.

There are some file-formats which are better handled by rio, but there are also some which switching would lose support for, specifically, HTML, XML, png, and jpeg.

Are there any plans to support these in rio? It could be relatively easy to swipe the code from `httr` itself!

Brendan

**Comment by brendan-R** [comment]
Well, I obviously hadn't had a good look through the source! Fantastic that they are supported, thanks again for the package!

**Comment by leeper** [comment]
@brendan-R Well, those particular formats are not entirely supported. HTML and XML, for example, will work if they're easily parsed to a data.frame. PNG and JPEG will produce an error that points users to the relevant import function. The idea for rio is to always return a data.frame or, alternatively, to fail, so I wouldn't recommend using it for arbitrary imports.
