### ISSUE TITLE
import from google sheets

### ISSUE THREAD

**Issue by chainsawriot** [leeper/rio#60]
https://github.com/maxconway/gsheet
https://github.com/jennybc/googlesheets

Should we implement this?

e.g.

```{r}
import("https://docs.google.com/spreadsheets/d/1I9mJsS5QnXF2TNNntTy-HrcdHmIF9wJ8ONYvEJTXSNo/edit#gid=0")
```

**Comment by leeper** [comment]
This is a good idea, but I'm hesitant to add a dependency here (those packages have a lot of functionality we don't need just for an import). I think we should be able to identify a spreadsheets URL and then modify it to retrieve the sheet as either XLSX or CSV by appending a `format=` argument to the URL:

 - https://docs.google.com/spreadsheets/d/1I9mJsS5QnXF2TNNntTy-HrcdHmIF9wJ8ONYvEJTXSNo/export?format=csv
 - https://docs.google.com/spreadsheets/d/1I9mJsS5QnXF2TNNntTy-HrcdHmIF9wJ8ONYvEJTXSNo/export?format=xlsx

Are Google Spreadsheets URLs always of a standardized form (so we can, for example, regex them)?

**Comment by jennybc** [comment]
When I revisit `googlesheets` in the new year, I can try to give you a clean function to do as you say above. You should be able to offer some simple read functionality (as csv and xlsx, at the least) for Sheets that do not require auth w/o needing to depend on `googlesheets`.

**Comment by leeper** [comment]
@jennybc :+1:

**Comment by chainsawriot** [comment]
https://github.com/maxconway/gsheet/blob/master/R/gsheet2text.R

This is the Google Sheets URL parser from the gsheet package. It can be rewritten without rvest and stringr dependency. rvest is only use to check the sheet has been shared or not and those stringr operations can be rewritten with base regex functions.

**Comment by leeper** [comment]
Closed by https://github.com/leeper/rio/pull/63

**Comment by leeper** [comment]
This was great! Really nice addition!
