### ISSUE TITLE
Create netcdf/hdf extension package

### ISSUE THREAD

**Issue by leeper** [leeper/rio#61]
Possibly through [the ncdf4 package](https://cran.r-project.org/web/packages/ncdf4/index.html). Worthwhile?

**Comment by leeper** [comment]
This can be a separate package, rio.hdf that can import:
 - [ ]  hdf5 via [h5](https://cran.r-project.org/web/packages/h5/index.html) and/or [rhdf5](http://bioconductor.org/packages/release/bioc/html/rhdf5.html)
 - [ ] netcdf via [ncdf4](https://cran.r-project.org/web/packages/ncdf4/index.html)

**Comment by mdsumner** [comment]
I have done a bit in this space already, one to read the header metadata in tidy form, the other to present NC vars as R arrays with [ ops etc. Would you want to expose subsetting by offset/stride, or just read all? What about dim vars? Raster package and GDAL in R have the most high level interfaces to these, though ferret is probably the best and most general. Maybe rio should leverage raster in the start?
