### ISSUE TITLE
Minor issue: function names

### ISSUE THREAD

**Issue by chainsawriot** [leeper/rio#64]
It is not an issue for users because only 3 functions are exported. 

I have revisited the code base recently and found there are series of `import.*` functions, `parse.*` functions, some underscore-separated functions (e.g. `remote_to_local`). Luckily, no camel-cased function.

It is a matter of taste on how to name functions in the R world and there is even a [research paper](https://journal.r-project.org/archive/2012-2/RJournal_2012-2_Baaaath.pdf) about it.

> What could help  might  be to raise  awareness in the R community about naming conventions; writers of books and tutorials on R could make a difference here by treating naming conventions when introducing the R language. What is most important, however, is to keep a consistent naming convention style within your code base, whether you are working on a personal project or developing a package

I think we should stick with one consistent style. Also, put that style in the CONTRIBUTING.md.

**Comment by leeper** [comment]
Good point. There's something of a logic to this, with the `import.*()` and `export.*()` functions using S3-like dot style (thus the discussion in https://github.com/leeper/rio/issues/42), which may be worth revisiting at some point if things get more complicated. The `_` notation of the internals is my preferred style, so I guess if this is important then all of the dot notation should be changed to underscores.

**Comment by jsonbecker** [comment]
FWIW, I find the `.` notation and `_` notation separation to be clear in this case.

If there is to be a style guide, language like:


> In general, `snake_case` is the preferred notation when naming variables, functions, and other objects. One exception is naming functions that are meant to be called primarily by other functions. In these cases, such as the `import.*`function, users are expected to interact directly only with `import()`, which then will appropriately dispatch to an internal function `import.*` that's appropriate to the data type being imported. This is done to mimic R's S3 multiple dispatch syntax since the design pattern is effectively similar. No functions intended to be directly called by external users should use `dot.notation`.

**Comment by leeper** [comment]
This will all be moot if we implement what I just suggested here: https://github.com/leeper/rio/issues/42#issuecomment-171471833

We'll use snake case for internal functions, none of which will be exported, and the current dot notation functions will be converted to `import.fmt()` and `export.fmt()` s3 methods.

**Comment by leeper** [comment]
This is resolved as of https://github.com/leeper/rio/commit/bc931ba8087133b53e89bbd11af7699f9f43a99d (on the s3classes branch, which will be merged shortly).
