### ISSUE TITLE
Import from markdown tables?

### ISSUE THREAD

**Issue by leeper** [leeper/rio#70]
Would this be a useful feature? I don't see a need to write markdown (because that's already supported by `knitr::kable()`, `xtable::xtable()`, `stargazer::stargazer()`, etc.).

**Comment by chainsawriot** [comment]
I think it can be useful, particularly in the case of importing from clipboard copy of markdown table source code.

For example I copy the markdown table source code from the readme.md of this repo and import it into R.

A similarly useful feature is importing from wikitable syntax when one copy-and-paste table source code from Wikipedia. For example:

```
{| class="wikitable"
|-
! '''singular'''
! '''plural'''
|-
| die Frau <small>(''woman'')</small>
| die Frau'''en'''
|-
| der Mann <small>(''man'')</small>
| die M'''ä'''nn'''er'''
|-
| die Kuh <small>(''cow'')</small>
| die K'''ü'''h'''e'''
|-
| der Globus <small>(''globe'')</small>
| die Glob'''en'''
|-
| der Atlas <small>(''atlas'')</small>
| die Atla'''nten'''
|-
| der Kuss <small>(''kiss'')</small>
| die K'''ü'''ss'''e'''
|-
| der Bus <small>(''bus'')</small>
| die Bus'''se'''
|-
| das Kabel <small>(''cable'')</small>
| die Kabel
|-
| das Auto <small>(''car'')</small>
| die Auto'''s'''
|-
| die Mitarbeiterin <small>(''female employee'')</small>
| die Mitarbeiterin'''nen'''
|-
| der Kaktus <small>(''cactus '')</small>
| die Kakt'''een'''
|}
```

**Comment by jennybc** [comment]
I think this could be handy and I feel like @sjackman proposed it once over in `readr` (unsuccessfully) but now I can find no trace of such a thing. Maybe I imagined that.

**Comment by leeper** [comment]
@jennybc worth a separate package to import here? Or something we should write internally?

**Comment by jennybc** [comment]
I have no idea! Maybe just do it here? What do you even do ... compile the table to HTML and then use `rvest` or something?

**Comment by leeper** [comment]
Yea, maybe something like that...I haven't really thought about it!

**Comment by sjackman** [comment]
I did propose that feature for `readr`. The pull request is over here: https://github.com/hadley/readr/pull/104

The patch works but needs a bit of TLC to rebase it onto master.

**Comment by jsonbecker** [comment]
We would have to specify which table format-- since tables are not a standard feature of Markdown, the rules of what constitute a table may be more complex than anticipated unless adopting one particular parser's flavor -- e.g. Github-flavored Markdown, MultiMarkdown, php-markdown, etc.

**Comment by jennybc** [comment]
This ⬆️ from @jsonbecker is why I made the admittedly weird suggestion to compile the table then extract via `rvest`. Outsource it 😋.

**Comment by sjackman** [comment]
Pandoc or GFM is my preferred table format. e.g.
https://help.github.com/articles/github-flavored-markdown/#tables
```
First Header  | Second Header
------------- | -------------
Content Cell  | Content Cell
Content Cell  | Content Cell
```

**Comment by leeper** [comment]
Rather than making this a part of rio, it seems like it should be a separate package that reads a variety of table-like but possibly unpleasantly formatted data structures. If such a package is developed, rio will import it.
