### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by njanetos** [leeper/rio#85]
When I try to save a data frame with many strings to SPSS format using rio (both the github and the CRAN version), there is some sort of memory issue and R crashes. For example, when I run this code, 
```
library(rio)

d = data.frame(x = rep(0, 2000))
for (i in 1:length(d)) {
    d[i] = "This is a test string of some length. This is a test string of some length. This is a test string of some length. This is a test string of some length. This is a test string of some length. This is a test string of some length. This is a test string of some length. This is a test string of some length. This is a test string of some length."
}

export(d, "test.sav")
```

R crashes with 

```
$ Rscript test.R

*** Error in `/usr/lib/R/bin/exec/R': free(): corrupted unsorted chunks: 0x000000000282ba20 ***
Aborted (core dumped)
```

This is on Ubuntu with R 3.2.2 and both the github and the CRAN versions.

**Comment by chainsawriot** [comment]
I can reproduce this in Debian 8.

It seems to be a problem of `haven::write_sav`. I can reproduce the memory leak with 

```{R}
haven::write_sav(d, "test.sav")
````

report it to hadley/haven

**Comment by leeper** [comment]
Thanks, @njanetos. Can you report this here: https://github.com/hadley/haven/issues with a link to this issue page?

**Comment by njanetos** [comment]
The problem is that the SPSS format does not naturally support strings longer than 255 characters. Haven uses a C library called ReadStat, WizardMac/ReadStat@1ab480a modifies the library so that now strings longer than 255 characters are truncated. Thank you both for your help.
