### ISSUE TITLE
Import/Export HTML Tables

### ISSUE THREAD

**Issue by leeper** [leeper/rio#86]
It would be nice to implement something ala `XML::readHTMLTable()`

**Comment by chainsawriot** [comment]
It can be done with rvest. But the problem is we need to assume the input html file has only 1 html table.

```{r}
require(rvest)
read_html("https://www.ssa.gov/oact/babynames/numberUSbirths.html") %>% html_nodes('table') %>% (function(x) x[[2]]) %>% html_table
```

**Comment by christophergandrud** [comment]
That is definitely the tricky bit. I guess the paradigm would be similar to sheets in an excel file, with a `table_number` argument that the user could specify?

**Comment by leeper** [comment]
The challenge is that depending on formatting, a document could appear to have one table but actually have many (and vice versa). We could start with an HTML export and then consider how to do importing.

**Comment by christophergandrud** [comment]
:+1:

**Comment by leeper** [comment]
Reimplement HTML write method using xml2
