### ISSUE TITLE
message when import zip files

### ISSUE THREAD

**Issue by cderv** [leeper/rio#93]
Hi, 

when I tried to import a csv in a ZIP file from a url, I get a message 

> Unrecognized file format. Try specifying with the format argument.

However, it work correctly and my CSV was read.
Zip seems not to be in the file format list wich work with `get_ext`.

For me getting a message like this one is not a goo sgn as user, thinking I made a mistake. It could be clearer to the user if the message is adapted to the situation. It could be a good idea to add something specific when working with zip files.

**Comment by leeper** [comment]
Thanks. Yes, we just need to add `.zip`, `.tar`, etc. extension to the list in [`get_type()`](https://github.com/leeper/rio/blob/master/R/utils.R#L1).
