### ISSUE TITLE
CSV export - don't quote strings

### ISSUE THREAD

**Issue by jabranham** [leeper/rio#95]
Hi, and thanks for the awesome package!

It would be helpful for me if exporting to a csv file had the option to not quote character strings. `readr::write_csv` does this by default, so perhaps a simple wrapper around that...?

**Comment by leeper** [comment]
rio uses `write.table()` for this, so you should be able to just pass a `quote = FALSE` argument via `...`:

```R
rio::export(iris, file = "iris.csv", quote = FALSE)
```

**Comment by jabranham** [comment]
Thanks. This is good enough to solve my current problem, though it doesn't look like `write.table` does this as "smartly" as `readr::write_csv` in the sense that the latter quotes values that contain a comma, quote, or newline character.

**Comment by leeper** [comment]
Ah. Well, that functionality will be supported by default once https://github.com/leeper/rio/issues/90 is implemented (basically when `data.table::fwrite()` is on CRAN).

**Comment by jabranham** [comment]
Great, and thanks again for the awesome package!
