### ISSUE TITLE
Implement write methods for XLSX and ODS

### ISSUE THREAD

**Issue by leeper** [leeper/rio#96]
And submit it them to the `readxl` and `readODS` packages, respectively.
- [ ] write xlsx method
- [x] write ods method

**Comment by jennybc** [comment]
Lurker here. Writing xlsx is a really big job. I'm up to my eyeballs in xlsx at this very moment. You might want to do a first pass with one of the packages that already does this. Or is it only offered by the ones that also have undesirable dependencies, e.g., Java? I can't remember. Do you want to write xlsx *de novo* or mutate an existing workbook?

**Comment by chainsawriot** [comment]
This one might be useful, because of its simplicity we can translate it into R.

https://github.com/mmulqueen/odswriter

**Comment by jsonbecker** [comment]
Any reason for a goal to remove `openxlsx`? In my experience, it's had the best speed and most options for working with Excel files.

**Comment by jennybc** [comment]
What degree of xlsx writing are you considering? "Data only" would be totally different (easier) than ... formatting, formulas, etc.

**Comment by leeper** [comment]
@jsonbecker I have a severe case of dependency aversion. It is sometimes too aggressive.

@jennybc Yes, I was thinking of basically being able to push a straightforward data rectangle into some kind of single-sheet template.

**Comment by jsonbecker** [comment]
@leeper a suggestion, if this is purely about reducing dependencies: 

Maybe with the S3 stuff up and running, it would make more sense to break out read/write methods that are not available in base R into a `rio_extras` package that imports those packages. It just strikes me that an Excel reader/writer is non-trivial and seems out of scope of the intent of `rio` as a standalone package to me.

**Comment by leeper** [comment]
`xml2` [now supports](https://blog.rstudio.org/2016/07/05/xml2-1-0-0/) creating XML documents

**Comment by iembry-USGS** [comment]
Is write_ods available yet? I attempted to export to .ods with the CRAN version of rio, but it didn't work. Thank you.

**Comment by leeper** [comment]
@iembry-USGS Support is not yet on CRAN. I'm pushing an update momentarily that will make that available here on GitHub.

**Comment by leeper** [comment]
Sounds like xlsx is being taken care of. https://github.com/leeper/rio/issues/145#issuecomment-284414309

**Comment by leeper** [comment]
Jeroen has given us [writexl](https://github.com/ropensci/writexl), also on CRAN.

**Comment by sda030** [comment]
If you allow me to reopen this issue, I want to question why your last message, before closing this thread, mentioned Jenny's writexl-package. 
If you are dependency-averse I would move from openxlsx to writexl as the latter has no dependencies (unless you count cpp11). openxlsx has 5 (though some are core packages)
writexl is twice as fast as openxlsx.
Github issues (currently 16) for writexl seem mostly centered around whether or not Clippy should be kept or removed from the help pages.. openxlsx has more open issues (due to larger scope).

On the other side, writexl has way fewer downloads compared with openxlsx and xlsx.
