### ISSUE TITLE
Importing a csv file with non comma separator

### ISSUE THREAD

**Issue by dannyparsons** [leeper/rio#99]
I can't seem to import a csv file when the separator is not a comma. Am I missing some simple? Since the README file states: 

> a CSV that is actually tab-separated will still be correctly imported.

Example:

```
df <- data.frame(X1 = 1:5, X2 = 101:105, X3 = LETTERS[1:5])
write.table(df, file = "tabbed_file.csv", sep = "\t", row.names = FALSE)
import("tabbed_file.csv")
```

This imports with a single column:

```
  X1"\t"X2"\t"X3
1  1"\t1\t101\t"A
2  2"\t2\t102\t"B
3  3"\t3\t103\t"C
4  4"\t4\t104\t"D
5  5"\t5\t105\t"E
```

fread can automatically detect the separator so I thought this would work.

Also tried `import("tabbed_file.csv", sep = "\t")`
but that gives an error:

> Error in import_delim(file = formal argument "sep" matched by multiple actual arguments

Which seems to be because `sep = ","` is hard coded into the `.import.rio_csv` method?

Doing a check for `missing(sep)` similar to what `import_delim` does and passing in `sep = "auto"` if missing instead of `sep = ","` would get the right functionality I think.

Update:
I just realised that `import("tabbed_file.csv", format = "tsv")` works. But since `fread("tabbed_file.csv")` also works, I would guess that `import("tabbed_file.csv")` detecting the tab is still the desired behaviour for rio?

**Comment by leeper** [comment]
This appears to be a bug. Thanks for reporting. I will investigate.

**Comment by sebastiansauer** [comment]
I seem to have the same problem (CSV with non-comma separator showing strange behavior):

`data(mtcars)
write.table(mtcars, file = "data/mtcars_s.csv", sep = ";")
m3 <- import("data/mtcars_s.csv", ";")`

The imported data.frame does not recognize the column names:
Warning message:
In fread(input = "data/mtcars_s.csv", sep = "auto", header = "auto",  :
  Starting data input on line 2 and discarding line 1 because it has too few or too many items to be column names or data: "mpg";"cyl";"disp";"hp";"drat";"wt";"qsec";"vs";"am";"gear";"carb"

packageVersion("rio")
[1] ‘0.5.10’

**Comment by dannyparsons** [comment]
I don't think this is a problem with non-comma separators:

```
data(mtcars)
write.table(mtcars, file = "mtcars_s.csv", sep = ",")
m3 <- import("mtcars_s.csv", sep = ",")
```

gives the same problem even with a comma as the separator.

If you look at the exported `mtcars_s.csv` file you will see that the column names are not lined up correctly. The column names start in column 1 even though they should start in column 2 (because the first column contains the row names). So the issue is with `write.table`. To fix this you can either do: 

1. `write.table(mtcars, file = "mtcars_s.csv", sep = ";", row.names = FALSE)`
so that row names are removed

2. `write.table(mtcars, file = "mtcars_s.csv", sep = ";", row.names = TRUE, col.names = NA)`
From the documentation for `write.table`: "If col.names = NA and row.names = TRUE a blank column name is added, which is the convention used for CSV files to be read by spreadsheets." So the row names are kept and have a blank column name so that the names line up correctly.

3. write.csv2(mtcars, file = "mtcars_s.csv")
Which is the same as 2 but uses a comma for the decimal point

1 and 2 will work with any separator. 

It does seem strange that the defaults for `write.table` would give incorrect column headers for csv files, but I guess that is why `write.csv` and `write.csv2` were created, so it seems safer in general to use them to write csv files instead of `write.table`.

**Comment by sebastiansauer** [comment]
Thanks; that sounds convincing.

Could you comment on the following (related) isse? I would like to export (via rio) a CSV but with a non-comma separator. Apparently, the following code does not work:

`rio::export(mtcars, file = "data/mtcars_s", ";")`

I thought it would (that's how I understood the help, where ";" as shortcut for format is mentioned. I'm unsure how to export a dataframe to a non-comma csv file via rio.

**Comment by leeper** [comment]
Suspect it's that the argument isn't named.

**Comment by sebastiansauer** [comment]
That's a reasonable guess, but this version did not work either:

`rio::export(mtcars, file = "data/mtcars_s", format = ";")`

yielding this message:

"Error in .export.default(file = file, x = x, ...) : Format not supported"

**Comment by leeper** [comment]
@sebastiansauer Please try with the latest version from Github, which should fix this issue.

**Comment by sebastiansauer** [comment]
Thanks! Works like a charme.
